### ISSUE TITLE
Show host_display_name and service_display_name

### ISSUE THREAD

**Issue by mrcnpdlk** [Icinga/icingaweb2-module-businessprocess#102]
Is any way/solution/hack to show this above information?
On business process and creating form is only host_name & service_name.

**Comment by AndreasO87** [comment]
Hello,
I also think, it would be better, to pick the display_name. 
What do you think? I could adapt this, if it is OK.

**Comment by unix0r** [comment]
I'm also looking for a solution to show the display_name instead of the host or service name :-)

@AndreasO87 
Do you have information about this?

**Comment by robertkrenn** [comment]
This would be really great. Where ever I set the display_name, it was to make the output in icingaweb2 more "human readable". And Business Processes are exactly that, to make context and relationships visble, so the display_name should really be used, or you should have the option to choose whether to use.

**Comment by nilmerg** [comment]
Hi,

yes, good idea. Use the `display_name` what it's supposed for. (Display purposes) Doesn't need to be configurable, since it's rather standard behavior.

If there are still volunteers, go ahead! :+1:
