### ISSUE TITLE
Provide restrictions

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2-module-businessprocess#103]

**Comment by dgoetz** [comment]
The module now includes basic restrictions by requiring a prefix which is a simple string. I would like to have this improved to be an array and for an administrative account something like "*" to override.

**Comment by Thomas-Gelf** [comment]
This issue has been obsoleted with #106. @dgoetz: even before those prefix-based restrictions there has been (hidden) support for very granular restrictions. Please see #98 for related details. I'll close this issue, please open new dedicated ones in case you still miss anything.

Thanks,
Thomas

**Comment by Al2Klimov** [comment]
"I'll close this issue" – @Thomas-Gelf
