### ISSUE TITLE
Assignments between non existent nodes are not visible

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-businessprocess#104]
See attached screenshot:

<img width="376" alt="bildschirmfoto 2017-01-27 um 19 54 36" src="https://cloud.githubusercontent.com/assets/3973350/22727566/d20d061a-edd9-11e6-93f6-981643eb3d9c.png">

**Comment by Al2Klimov** [comment]
As investigated w/ @mwaldmueller: This has been fixed.
