### ISSUE TITLE
Users without Permission "businessprocess/modify" can unlock and modify BPs

### ISSUE THREAD

**Issue by xam-stephan** [Icinga/icingaweb2-module-businessprocess#107]

**Comment by Thomas-Gelf** [comment]
I wanted to reply that it wouldn't help much as he wouldn't be allowed to store it - but that's not true, required assertions are missing in the code. Thanks for reporting this!

**Comment by Thomas-Gelf** [comment]
Hint: "unlock" should still be allowed, it is required for the simulation mode

**Comment by Thomas-Gelf** [comment]
I pushed a couple of commits that should address this. In case you can still find related issues please let me know!
