### ISSUE TITLE
reference a bp from another file does not work

### ISSUE THREAD

**Issue by lbetz** [Icinga/icingaweb2-module-businessprocess#108]
I tried to use a reference in my config file

a = @config:bp

and I got:

Fatal error: Call to undefined method Icinga\Module\Businessprocess\BpConfig::retrieveStatesFromBackend() in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/ImportedNode.php on line 69

**Comment by Thomas-Gelf** [comment]
retrieveStatesFromBackend() does no longer exist, this is a leftover from a before-2.0 refactoring
