### ISSUE TITLE
Info URL not working

### ISSUE THREAD

**Issue by slalomsk8er** [Icinga/icingaweb2-module-businessprocess#113]
After filling out the Info URL of a node the URL is in the configuration and gets displayed on mouse over of the link.
But i guess Icingaweb2 removed http://hostname from the href of the anchor and thus breaks the link.

**Comment by JensKrone** [comment]
here the same. Does anyone have a solution? Tom?

**Comment by Al2Klimov** [comment]
As investigated w/ @Thomas-Gelf:

BP's `Url` class swallows external URLs' hosts.

**Comment by Al2Klimov** [comment]
I'm going to fix this after https://github.com/Icinga/icingaweb2/pull/3180.

**Comment by Al2Klimov** [comment]
Hello everyone,

please could you test the above changes w/ Icinga Web, either the current master or 2.5.1 – once it has been released.

Best,
AK

**Comment by Al2Klimov** [comment]
@JensKrone Hmm... I seem not to be able to assign you as well.

**Comment by slalomsk8er** [comment]
Works in branch bugfix/info-url-not-working-113 but not in master.
