### ISSUE TITLE
State in overview

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-businessprocess#116]
If a Business Process contains only one node, it's current state should be visible in the overview.

**Comment by Al2Klimov** [comment]
As discussed w/ @mwaldmueller (offline):

1. This would be useful for BPs w/ > 1 nodes, too.
2. We'll wait for *someone* to pay for this.

**Comment by nilmerg** [comment]
Seems somewhat stale to me and without any further clarification on what this all is about (States of only children **are** visible??) I consider this closed.
