### ISSUE TITLE
[dev.icinga.com #8586] Add a config switch for external_info, disabled per default

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#12]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8586

**Created by tgelf on 2015-03-03 14:43:16 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-06-24 13:35:19 +00:00 (in Redmine)_

---

The legacy BPaddon allows one to define commands for external execution in external\_info. I'd like to fade out this feature as it is insecure and a performance issue. As we might not be allowed to do so for compatibility reasons, I opt for a config flag disabling this feature per default. We could also just show the info text per default, as many people use this feature only to shell-echo 'Some instructions'.

Best,
Thomas

**Comment by nilmerg** [comment]
I don't know since when, but this is currently not used anywhere. i.e. it's parsed but not utilized.

I guess it's now time to get rid of this. @Thomas-Gelf  right?
