### ISSUE TITLE
PHP Fatal errror: Memory allocation

### ISSUE THREAD

**Issue by arcadesolutions** [Icinga/icingaweb2-module-businessprocess#121]
BP-Module is unable to display a newly created businessprocess which is a multilevel process with nine stages.

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 130968 bytes) in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpNode.php on line 176

It doesn't make a difference what value is set, here 2048MB e.g.  I was able to display the process with about eight stages with 256MB memory.

It's the latest commit ec813683ab320e843b8a820a93ca016979e214f3 with PHP 5.4.45 and Apache 2.4.6-45

**Comment by Thomas-Gelf** [comment]
Hi @arcadesolutions,

nine levels and more should be no problem at all. Guess there is a loop, however in theory loop detection should catch this. Could you please share your process config file with me, eventually in private? You'll find it in `/etc/icingaweb2/modules/businessprocess/processes`.

Thanks,
Thomas

**Comment by arcadesolutions** [comment]
Hi Thomas,

Thanks for the quick reply, can i send the config to thomas@gelf.net<mailto:thomas@gelf.net>?

Regards
Reto

Von: Thomas Gelf [mailto:notifications@github.com]
Gesendet: Dienstag, 21. März 2017 10:40
An: Icinga/icingaweb2-module-businessprocess <icingaweb2-module-businessprocess@noreply.github.com>
Cc: Reto Zeder <reto.zeder@arcade.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [Icinga/icingaweb2-module-businessprocess] PHP Fatal errror: Memory allocation (#121)


Hi @arcadesolutions<https://github.com/arcadesolutions>,

nine levels and more should be no problem at all. Guess there is a loop, however in theory loop detection should catch this. Could you please share your process config file with me, eventually in private? You'll find it in /etc/icingaweb2/modules/businessprocess/processes.

Thanks,
Thomas

**Comment by Thomas-Gelf** [comment]
Yes, that's fine. In case you're required to use a secure channel let me know, I can send you a protected upload link.

**Comment by Thomas-Gelf** [comment]
Thank you for the configuration file. The problem is in the `getMissingChildren() / isMissing()` code. The controller fires them before `reCalculateState()` is triggered, and that's currently the only place where loop detection takes place.

With a slight change to the code it correctly states:

    Loop detected: peering_xxx -> internet_xxx -> internet_yyy -> peering_xxx

I'll push the fix as soon as I feel confident that it has no side-effects. In the meantime I guess fixing the loop should fix the issue for you.

Thanks for reporting this!
