### ISSUE TITLE
Simulation only allows to change one node

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-businessprocess#122]
Simulation mode only allows to change one node. If you select another you get the state from the already changed node in the selector and changing it changes the already changed and not the selected one.

This is also not reset by dismissing the simulation, only by leaving the module.

I think this has something to do with the changed noded stored in the URL.

**Comment by theFeu** [comment]
I can't reproduce this issue, if this is still happening to you with the current master, please open a new issue :)
