### ISSUE TITLE
free arrangable objects

### ISSUE THREAD

**Issue by darmagan** [Icinga/icingaweb2-module-businessprocess#123]
Hi,

at the moment the objects in the tree view are sorted alphabetically. It would be nice if they could be arranged freely with drag & drop so that the important objects are always on top.
It's possible to rename them for this, but a feature like this would be a cleaner solution.

Regards

**Comment by darmagan** [comment]
or a priority value for the objects, which is calculated in the sorting process. I think that's easier to implement.

**Comment by Tontonitch** [comment]
same as #82
