### ISSUE TITLE
Error Node "abcd" has been defined more than once

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2-module-businessprocess#128]
Hello,
After creating a new process node and a related subprocess node, storing them, I face the following error when trying to go to the Business Process view:
```
#0 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Modification/NodeCreateAction.php(98): Icinga\Module\Businessprocess\BpNode->addChild(Object(Icinga\Module\Businessprocess\BpNode))
#1 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php(153): Icinga\Module\Businessprocess\Modification\NodeCreateAction->applyTo(Object(Icinga\Module\Businessprocess\BpConfig))
#2 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Controller.php(208): Icinga\Module\Businessprocess\BpConfig->applyChanges(Object(Icinga\Module\Businessprocess\Modification\ProcessChanges))
#3 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(80): Icinga\Module\Businessprocess\Web\Controller->loadModifiedBpConfig()
#4 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\ProcessController->showAction()
#5 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#6 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#9 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#10 {main}
```
I guess the subprocess node name "Databases" was already used, and that situation generates an error.

How to fix that now?
Also, that would be good to prevent such a situation by not allowing to use an already existing node name when creating a node.

BR,
Yannick

**Comment by Tontonitch** [comment]
Refreshing the page on my browser had no effect, but closing and reopening the browser page fixed the issue... strange

**Comment by dgoetz** [comment]
I was also hit by this several times without having a real duplicate definition. Sometimes while editing, sometimes after saving an edited version. 
As far as I could debug this, it has nothing to do with my configuration, so it could only be something in "memory". This is my conclusion as I could edit it from a private tab without the error message or download my configuration when I was able to save and upload the same configuration (with another name) without getting an error. 
It happened to me when I only added multiple services to one node, but also after creating several layers of nodes, so I found no real way to reproduce it, yet.

**Comment by Thomas-Gelf** [comment]
The businessprocess module keeps all Changes in your Session, but related to your browser tab. So, every new browser tab can have it's very own history of changes. You can reproduce this error by adding a component that already makes part of a businessprocess node another time. This will not be stored, but kept in your tabs stacked "changes" history, re-applied at every refresh - and as it fails every time you get no chance to fix it, rather then going to another tab.

**Comment by dgoetz** [comment]
Ok, this explains my trouble on reproducing it and why I could see the process in a new tab and then the error came seconds after. 
But I also got this without a real duplicate. In one case I added one Hoststatus and three Services and I got the error message. So perhaps it did not reset the changes history for some reason? Browser is Firefox 53 on Fedora. So it was no show stopper at all to me, but somehow irritating.

**Comment by Thomas-Gelf** [comment]
It remembers all changes you did in that single browser tab unless you either store or dismiss them

**Comment by Thomas-Gelf** [comment]
And yes, it's irritating and should be fixed.

**Comment by Fiiti** [comment]
+1   

Happy that the solution is quite easy and was already written here!

**Comment by wols** [comment]
Please mark already existing entries (hosts, services) as selected in the dropdown list..

**Comment by Thomas-Gelf** [comment]
Update: as of v2.1.0 it doesn't break, but allow to dismiss pending changes. IMO to finally fix this we should not allow to create duplicate nodes at all
