### ISSUE TITLE
[dev.icinga.com #8588] Filter process views

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#13]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8588

**Created by tgelf on 2015-03-03 15:31:48 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2017-01-11 13:58:52 +00:00 (in Redmine)_

---

It would be great to be able to filter process views by state or object name, allowing one to show only a partial tree with only those objects that match the given filter. The filter should of course NOT influence the calculated state.

Cheers,
Thomas

**Comment by nilmerg** [comment]
Duplicate of #329
