### ISSUE TITLE
Warning states for processes

### ISSUE THREAD

**Issue by mkayontour** [Icinga/icingaweb2-module-businessprocess#131]
Hi, it would be nice to have "warning" states for Businessprocesses. So i can notify myself before the process stopped working!

Furthermore to have a good overview over all processes and their current health.

What do you think about that feature?

**Comment by nilmerg** [comment]
This may only apply to businessprocess configurations which use hard states to calculate states. When calculating states such a process may peek at a node's soft state then. If this is non-ok it may set itself into a simulation state or such.

Sounds interesting and not entirely impossible to me. Though, requires some effort in regards to impact strength as well as front-end visualization and CLI integration.

**Comment by nilmerg** [comment]
@mkayontour Just had another look, the CLI command `process check` provides a switch to override the state type to check for. May this already be the feature you're looking for?
