### ISSUE TITLE
Cannot remove a node

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2-module-businessprocess#132]
Thying to remove a node, it fails: 

![image](https://cloud.githubusercontent.com/assets/600025/25746935/ee7f25f2-31a5-11e7-98a3-19a6794250ce.png)

![image](https://cloud.githubusercontent.com/assets/600025/25746949/ff460428-31a5-11e7-8d80-f4dacd40e671.png)

produces: 

`Fatal error: Call to a member function getName() on a non-object in /usr/share/icingaweb2/modules/businessprocess/application/forms/DeleteNodeForm.php on line 138`

BR,
Yannick

**Comment by Al2Klimov** [comment]
Hi @Tontonitch,

do the above changes solve your problem?

Best,
AK

**Comment by Tontonitch** [comment]
Hello,
I thought it was fixed.
Just to be sure I did a test:
1. create a new process "Test1"
2. added a new node A of type host to it 
3. tried to remove the process "Test1" -> fails with error1 (see below)
4. tried to remove the node A -> successful
5. tried to remove the process (empty now) -> still fails with error1
6. opened another browser (to avoid cache issues) and again tried to remove the process (empty now) -> still fails with error1

error1 is:
`Fatal error: Uncaught Error: Call to a member function getName() on null in /usr/share/icingaweb2/modules/businessprocess/application/forms/DeleteNodeForm.php:138 Stack trace: #0 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Form/QuickForm.php(336): Icinga\Module\Businessprocess\Forms\DeleteNodeForm->onSuccess() #1 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(222): Icinga\Module\Businessprocess\Web\Form\QuickForm->handleRequest() #2 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(107): Icinga\Module\Businessprocess\Controllers\ProcessController->loadActionForm(Object(Icinga\Module\Businessprocess\BpConfig), NULL) #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\ProcessController->showAction() #4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction') #5 /usr/share/icingaweb2/library/vendor/Zen in /usr/share/icingaweb2/modules/businessprocess/application/forms/DeleteNodeForm.php on line 138`

**Comment by Tontonitch** [comment]
Updated the module with last git clone (just in case), but still the same issue:
`Fatal error: Uncaught Error: Call to a member function getName() on null in /usr/share/icingaweb2/modules/businessprocess/application/forms/DeleteNodeForm.php:138 Stack trace: #0 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Form/QuickForm.php(336): Icinga\Module\Businessprocess\Forms\DeleteNodeForm->onSuccess() #1 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(226): Icinga\Module\Businessprocess\Web\Form\QuickForm->handleRequest() #2 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(111): Icinga\Module\Businessprocess\Controllers\ProcessController->loadActionForm(Object(Icinga\Module\Businessprocess\BpConfig), NULL) #3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\ProcessController->showAction() #4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction') #5 /usr/share/icingaweb2/library/vendor/Zen in /usr/share/icingaweb2/modules/businessprocess/application/forms/DeleteNodeForm.php on line 138`

**Comment by Al2Klimov** [comment]
Did you try the `master` branch or `bugfix/cannot-remove-a-node-132`?

**Comment by Tontonitch** [comment]
Oh, good point :confused:
cloned again but this time the correct branch.
tested again, and now it's working, I can delete the node.
Great! :thumbsup:
