### ISSUE TITLE
Increase size of tiles dynamically

### ISSUE THREAD

**Issue by AndreasO87** [Icinga/icingaweb2-module-businessprocess#135]
Hello,
as we have the overview of the business process nodes shown on a TV-screen, it should be readable by everyone, who looks at it. If we have only a few nodes, the size is very small to read.
So it would be nice, if the tile size would adapt itself based on the free space and based on the sum of tiles.
It should be zoomed in, until you would have to scroll, in order to see the next element.
Of course you would have to define a minimum size.
What do you think about this feature?

**Comment by Thomas-Gelf** [comment]
It already adjusts the size dynamically, but only with a very few slightly differing steps. It should get about 20% bigger with less or equal than 6 tiles, and the size is reduced by 15% when there are more than 12. But those sizes have mainly been figured out to work smoothly when rendered in "normal" containers, not in full-screen mode.

Before digging deeper into this, and given that Icinga Web 2 (including all of it's modules) is responsive: couldn't you just zoom the browser on your TV screen to get what you want? (multiple times `CTRL-+` or similar)

**Comment by lazyfrosch** [comment]
I guess there are 2 problems:

* the labels are too small, just increase the text size, not the tile size
* colors could be improved, some are really hard to read

Will post a PR with screenshots and suggestions

**Comment by lazyfrosch** [comment]
![bildschirmfoto von 2017-06-01 19-11-37](https://cloud.githubusercontent.com/assets/121874/26691638/2ea31fe0-46fe-11e7-839a-f050a7e715d6.png)

**Comment by lazyfrosch** [comment]
![bildschirmfoto von 2017-06-01 19-12-41](https://cloud.githubusercontent.com/assets/121874/26691703/676fc742-46fe-11e7-8f60-75bfe87a8f4f.png)

**Comment by lazyfrosch** [comment]
This could be done by a flex design of the tiles.

Check https://github.com/Icinga/icingaweb2-module-toplevelview/blob/master/public/css/module.less and look for "flex"

**Comment by Thomas-Gelf** [comment]
Would be helpful, sure. Unfortunately our current policy is no flex unless we drop support for some "special" browsers - and define rules of how and whether we want to work around various nasty flex-related bugs.
