### ISSUE TITLE
DOS/Windows newlines break UI

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-businessprocess#136]
At least a problem while parsing meta data, only `\n` is stripped away.

The title gets blocked by Icingaweb2, because it contains `\r`

![bildschirmfoto von 2017-05-31 13-16-52](https://cloud.githubusercontent.com/assets/121874/26629633/7dc31086-4603-11e7-9a96-633f179a41c1.png)

To reproduce:

    unix2dos myprocess.conf

**Comment by Thomas-Gelf** [comment]
At least our last bastion, the Exception making sure that no one injects dangerous data into our headers did it's job :laughing:. We shouldn't need it, by the end - but unless we have a better title handling (JavaScript is involved here) it's good that we catch such errors. The error message could be friendlier of course ;-) I'll push a fix for this.

**Comment by Thomas-Gelf** [comment]
@lazyfrosch: could you please give this a try?
