### ISSUE TITLE
[dev.icinga.com #8589] Introduce a new node type: FilteredObjectsNode

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#14]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8589

**Created by tgelf on 2015-03-03 15:42:42 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2015-06-24 13:35:20 +00:00 (in Redmine)_

---

I want to be able to create a nodes in a way allowing me to not define objects one by one but by assigning a specific monitoring object filter like host=db\*&service=ping. While this first part will be pretty easy, it doesn't suffice. Most people will very soon feel the desire to automagically create multiple node definitions based on specific patterns.

Immagine a structure like this one:

    web1 = tomcat1;jmx & tomcat1;web
    web2 = tomcat2;jmx & tomcat2;web
    ...
    web14 = tomcat14;jmx & tomcat14;web
    web = web1 | web2 | ... | web14

You cannot solve this by just stating something like:

    web = (host=tomcat*&(service=web|service=jmx)). 

This would lead to a completely different logic and would not be what you intended to achieve. One possible way to configure what we had in our mind could look as follows:

    web* = tomcat*;jmx & tomcat*;web
    web = 1 of: web*

Best,
Thomas

---

**Relations**:

* relates [#8589](https://dev.icinga.com/issues/8589)

**Comment by nilmerg** [comment]
Duplicate of #328
