### ISSUE TITLE
Memory allocation issue

### ISSUE THREAD

**Issue by mrcschilling** [Icinga/icingaweb2-module-businessprocess#146]
Hello, I am using 
icinga2 - 2.7.0
apache - 2.4.6
icingaweb2 - 2.4.1
icinga director - git master branch latest
centOS 7.4
mariaDB latest

I created a template, which maybe is importing itself and therefore creating a loop.

Everytime I try to access the template to change it, the following message is shown:

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /usr/share/icingaweb2/modules/director/library/Director/Resolver/TemplateTree.php on line 243`

If I try to restore the former object in the activity log this error is shown:
`icinga_service has a multicolumn key, array required (DbObject.php:834)`

It seems to be quite similar to [#121](https://github.com/Icinga/icingaweb2-module-businessprocess/issues/121)

Thank you

**Comment by lippserd** [comment]
Hi,

Sorry but this is the wrong project for the issue. Please create a new issue for the director [here](https://github.com/Icinga/icingaweb2-module-director/issues/new).

Best regards,
Eric
