### ISSUE TITLE
"Host not found" error stack for users not allowed to see a host/service node details

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2-module-businessprocess#147]
Our helpdesk has an account in icingaweb2 and can access a specific Business Process in order to check that business applications are available.
It works well, however they get an error when clicking on a host/service after going through all the layers of a particular service. See the screenshot.
The error is due to the fact that this helpdesk user is not allowed to view hosts / services.
Instead of a 'Host not found' error stack, I would expect a 'Not allowed action' error well rendered.

## Expected Behavior

'Not allowed action' error well rendered (not a stack).

## Current Behavior

'Host not found' error stack
```
#0 /usr/share/php/Icinga/Exception/IcingaException.php(41): ReflectionClass->newInstanceArgs(Array)
#1 /usr/share/php/Icinga/Web/Controller.php(78): Icinga\Exception\IcingaException::create(Array)
#2 /usr/share/icingaweb2/modules/monitoring/application/controllers/HostController.php(33): Icinga\Web\Controller->httpNotFound('Host not found')
#3 /usr/share/php/Icinga/Web/Controller/ActionController.php(139): Icinga\Module\Monitoring\Controllers\HostController->init()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}
```
## Steps to Reproduce (for bugs)

1. create an "helpdesk" icingaweb2 user with not host/service object permissions
2. as admin, create business process with a process node and a related host node
3. allow the helpdesk user to view this business process
4. as helpdesk user, go through the business process -> process node -> host node. The host node details will produce this error

## Your Environment

* Module version (System - About): businessprocess 2.1.0
* Icinga Web 2 version and modules (System - About): IcingaWeb2 2.4.2
* Icinga 2 version (`icinga2 --version`):
* Operating System and version:
* Webserver, PHP versions:

**Comment by Tontonitch** [comment]
![error](https://user-images.githubusercontent.com/600025/32007705-9b29d388-b9aa-11e7-80cd-4991d7f94cdd.png)

**Comment by dnsmichi** [comment]
You should be able to disable stack traces in the global configuration, or on a per user basis.

**Comment by Tontonitch** [comment]
Hello Michael,
I've tried to disable "Show Stacktraces" in the user's perferences, but the stack is still shown (tested with a browser restart to be sure)
I tried to disable "Show Stacktraces" in the global configuration, but each time I save the change the option is back to the original state (crossed).
I will check if I can find the reason of that.

**Comment by Tontonitch** [comment]
Ok.

* when I cross the "Show Stacktraces", and save the change, in /etc/icingaweb2/config.ini the line show_stacktraces = "1" appears
* when I uncross the "Show Stacktraces", and save the change, in /etc/icingaweb2/config.ini the line show_stacktraces = "1" disappears

In order to have a correct configuration shown in icingaweb2 UI, I added the line show_stacktraces = "0" in /etc/icingaweb2/config.ini

**Comment by Tontonitch** [comment]
So, after some checks, 
* after forcing the show_stacktraces = "0" in the global configuration, the stack traces are not shown.
* after playing with the show stacktraces option in the user's perferences, I cannot make it working on that user scope. Maybe there is something not working fine there.

**Comment by Al2Klimov** [comment]
Hello @Tontonitch and thank you for your report!

the permissions conflict is indeed a problem.
The stacktrace stuff isn't a BP problem, but a framework problem.
Feel free to open an issue for that in [the respective tracker](https://github.com/Icinga/icingaweb2/issues/new).

Best,
AK
