### ISSUE TITLE
[dev.icinga.com #8591] Permissions and restrictions

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#15]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/8591

**Created by tgelf on 2015-03-03 17:06:45 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _2.0.0_
Last Update: _2017-01-11 23:47:28 +00:00 (in Redmine)_

---

We should at least distinct between editors and readonly users.

Best,
Thomas

---

**Relations**:

* duplicates [#8591](https://dev.icinga.com/issues/8591)
* blocks [#8591](https://dev.icinga.com/issues/8591)

**Comment by Thomas-Gelf** [comment]
The only missing part here is documentation, will be handled with #84.
