### ISSUE TITLE
Check command requires '--config' with more than one files.

### ISSUE THREAD

**Issue by wols** [Icinga/icingaweb2-module-businessprocess#154]
```
$ ls /etc/icingaweb2/modules/businessprocess/processes/
home_ntp.conf  home_vdr.conf
```
```
$ icingacli businessprocess process check home_ntp_server
Business Process OK: NTP Server
$ icingacli businessprocess process check --config=home_ntp home_ntp_server
Business Process OK: NTP Server

$ icingacli businessprocess process check home_vdr_proc
ERROR: Exception in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php:518 with message: The node "home_vdr_proc" doesn't exist
$ icingacli businessprocess process check --config=home_vdr home_vdr_proc
Business Process OK: Processes
```

## Expected Behavior
Option `--config` only needed for the same node name in multiple confi files.

## Current Behavior
Node names only in first file found without option?

## Environment
* Module version: 2.1.0
* Icinga Web 2 version: 2.4.1
* Icinga 2 version: 2.6.3
* Operating System: Gentoo Linux
* Webserver, PHP versions: apache-2.4.27, php-7.0.21

**Comment by nilmerg** [comment]
Hi,

the check command would need to scan every single file in the worst case. That's ineffective and just supports a user's laziness.

This check command is most probably only something that's called by Icinga and alikes. It's not unreasonable to add this switch to the configured command line once and be happy.
