### ISSUE TITLE
Invalid operator DEG

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2-module-businessprocess#159]
## Expected Behavior

Some docs about the sense of this operator.

## Current Behavior

Selecting this operator breaks my workflow.

## Possible Solution

I'd like to hear one from you, @Thomas-Gelf.

## Steps to Reproduce (for bugs)
1. Create a new BP
2. Create a new node w/ operator DEG
3. `Got invalid operator: <`

## Context
Research for #11.

## Your Environment
Latest bleedig edge stuff only.

**Comment by theFeu** [comment]
Will remove the option as discussed offline with Tom.
