### ISSUE TITLE
Fixing a Process with a Loop

### ISSUE THREAD

**Issue by cflinspach** [Icinga/icingaweb2-module-businessprocess#161]
We created a node loop and got this error:

![image](https://user-images.githubusercontent.com/4700533/34223787-71526542-e575-11e7-89ab-5512cf6d9e9f.png)

It was a test so we weren't to worried about it but the only way we could find to fix it was changing the URL from `show?config=NOC-Test` to `config?config=NOC-Test` then deleting it. 

Here's the config:
![image](https://user-images.githubusercontent.com/4700533/34224110-9160ea7e-e576-11e7-9826-837390ca02ac.png)

Is that the recommended way to fix it or are the configs stored somewhere that we can edit them to fix just the loop? 

Edit: We just updated this module this morning from the Master branch.

**Comment by lippserd** [comment]
Hi,

You find the configuration files beneath `/etc/icingaweb2/modules/businessprocess/processes/`.

@Al2Klimov Is this also fixed once #157 is merge?

Best regards,
Eric

**Comment by Al2Klimov** [comment]
@lippserd Yes, I think so.

**Comment by ccallawa** [comment]
Hi, I just thought I would share the minimal number of steps to reproduce this bug on v2.1.0.  There should be a check, but for me also the phrases "Existing Process" and "New Process Node" don't really capture what's supposed to be going on.

Create a new Business Process and fill in the fields
Click on "Add" to create a new root node
  Name: my-root-node
  Title: My Root Node
  Click to add it, then click (twice) to store it
Select My Root Node, unlock it and use the button to add another node
  It says "Add a node to My Root Node"
  For Node type, choose "Existing Process"
  In the Process nodes box, choose "my-root-node"
  Click to add it
Fatal error:   Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpNode.php on line 177
Business Processes are now dead until you recover by deleting or editing the file .../icingaweb2/conf/modules/businessprocess/processes/
