### ISSUE TITLE
Add icons to process badges

### ISSUE THREAD

**Issue by wols** [Icinga/icingaweb2-module-businessprocess#163]
A great relief effort for operators with red-green visual impairments would be additional icons on the badges:

![1301_tile-view_icons](https://user-images.githubusercontent.com/764167/34650934-06a21710-f3c1-11e7-847c-57a418382d35.png)

**Comment by nilmerg** [comment]
I would rather add a theme that adjusts these colors instead. Please create a new issue for that if you feel that's reasonable.
