### ISSUE TITLE
Showing the PlugIn Output in ServiceNode Badge

### ISSUE THREAD

**Issue by unix0r** [Icinga/icingaweb2-module-businessprocess#164]
Hey guys, i have a panel with a couple of Services as ServiceNodes and it would be great, to have the possibility to show the plugin output in the service Node.

The current view is: $this->hostname . ': ' . $this->service
![servicenode](https://user-images.githubusercontent.com/4679329/34763846-d96ba49a-f5ec-11e7-829d-aeeaf186177f.png)

![servicenodepluginoutput](https://user-images.githubusercontent.com/4679329/34763766-8b454e88-f5ec-11e7-9daf-860f1b20afdf.png)

So the Node would show Store_TotalOrders and the Output of 4550 in a new line.

I checked the ServiceNode.php, but there is no variable with the information of the plugin output.

Does anybody know, how to display the plugin output on this ServiceNode?

**Comment by nilmerg** [comment]
Hi,

did you consider the possible length of plugin output? Even if we're only talking about the first line?

Issue #197 even talks about customizable tile sizes. :laughing: 

I guess that's too difficult to realize and not necessary as it's possible to reach the plugin output by clicking on the tile.
