### ISSUE TITLE
distributed monitoring: icingacli not available

### ISSUE THREAD

**Issue by wols** [Icinga/icingaweb2-module-businessprocess#165]
I have a distributed monitoring setup.
Checks are running on icinga2 core nodes, but `icingacli` is on web nodes only.
Any hints?

## Expected Behavior
Business Process Service Check: OK
```
template Service "businessprocess" {
    check_command = "icingacli-businessprocess"
}
```
## Current Behavior
Plugin Output
```
execvpe(/usr/bin/icingacli) failed: No such file or directory
```
## Environment

* Module version (System - About): 2.1.0
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): 2.8.1-1
* Operating System and version: CentOS

**Comment by dnsmichi** [comment]
You need to install the `icingacli` package on the nodes where it should be executed.

**Comment by dnsmichi** [comment]
Why not just try it out?

**Comment by wols** [comment]
PHP rollout is not planned there.

**Comment by dnsmichi** [comment]
Well, this is a requirement by icingacli on its own. It uses the Icinga Web 2 framework libraries and is written in PHP.

**Comment by wols** [comment]
Dependencies noted. Thank you!
