### ISSUE TITLE
Business process structure in icinga IDO

### ISSUE THREAD

**Issue by bw00sy** [Icinga/icingaweb2-module-businessprocess#170]
Hi,

Is there a plan to move away from the text file configuration of business processes and to the Icinga IDO, or have a record in the IDO defining business processes? 

This would be helpful from a reporting point of view to determine what caused SLA breaches of Business Processes over a period. For example: - I would like to report on a business process that wasn't 100% available over a period, and then the reasons why. The server "A1" experienced a cpu threshold for 10% of the time and server "B1" a memory limitation for 20% of the time. All of these services are available via Icinga (IDO), but not linked directly to the business process when using a single "service" to query the Business Process as an entity. I have created a "dummy" host with a service, checking the business process, and it is accurately calculating the availability of my business process. However, when reporting, it would really help to be able to have all the sub processes to report on too.

My first thought is to create an additional **object type** (hosts, services, business processes) in inciga_objects table with a separate business objects table that has a record of the object_id's and their hierarchy in the business process.

Any thoughts?

**Comment by nilmerg** [comment]
Hi,

I've recently played around with this topic. From a performance point of view this is a bad idea, as the additional round-trip-time makes storing businessprocess configurations in the database way slower than in local text files.

If we're doing this at all, then in a separate database. This has nothing to do with the IDO itself. Linkage must be done manually either way.
