### ISSUE TITLE
New business processes can not be queried with icingacli - but old ones are working

### ISSUE THREAD

**Issue by Fiiti** [Icinga/icingaweb2-module-businessprocess#185]
## Current Behavior
I created a business process (bp)  with two nodes a year ago and everything is going fine. I can also query this easy with checkcommand by icinga2 services - what the main target is.

Now I wanted to create new bp - which apparently also run via GUI - but not by check command or by bash command icingacli.

## My environment
Ubuntu 16.04LTS
Icinga Web2 2.6.1
Director 1.4.0
Businessprocess 2.1.0

### As first an overview (list) of my bp:
**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#**
 icingacli businessprocess process list
Anmeldeservices (anmeldeservices)
Mailsystem

**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#** icingacli businessprocess process list Mailsystem
Exchange
Mail-Crypt (Mail_Crypt)

**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#**

_Note: "Exchange" and "Mail_Crypt" bp are the new ones._

### My attemp to ask the new "Exchange" or "Mail_Crypt" bp
**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#** icingacli businessprocess process check "Exchange" --details
ERROR: Exception in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php:518 with message: The node "Exchange" doesn't exist

**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#** icingacli businessprocess process check "Mail_Crypt" --details
ERROR: Exception in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php:518 with message: The node "Mail_Crypt" doesn't exist

**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#**

### The same with an "old business process" - everything is fine here:
**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#** icingacli businessprocess process list anmeldeservices
Backnang Anmeldeserver (backnanganmeldeserver)
Dienste
Etagenverteiler (etagenverteiler)
Hardware
Haupt-Verteiler (hauptverteiler)
Server Verteiler (SwitchVerteiler)
Teltow Anmeldeserver (teltow_anmeldeserver)
**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#** icingacli businessprocess process check "backnanganmeldeserver" --details
Business Process OK: Backnang Anmeldeserver
**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#** icingacli businessprocess process check "teltow_anmeldeserver" --details
Business Process OK: Teltow Anmeldeserver
**root@TL01-Nagios01:/etc/icingaweb2/modules/businessprocess/processes#**

#### Conf File NEW bp
  1 ### Business Process Config File ###
  2 #
  3 # Title           : Mailsystem
  4 # Description     : E-Mail relevante Dienste
  5 # Owner           : zenzh
  6 # AddToMenu       : yes
  7 # Backend         : icinga
  8 # Statetype       : hard
  9 #
10 ###################################
11
12 Exchange = TL01V-EXC10.TLTGES.local;Hoststatus
13 display 1;Exchange;Exchange
14 Mail_Crypt = TL01V-CryptMGMT.TLTGES.local;Hoststatus
15 display 1;Mail_Crypt;Mail-Crypt

#### Conf File old bp
1 ### Business Process Config File ###
  2 #
  3 # Title           : Anmeldeservices
  4 # Description     : Anmeldedienste
  5 # Owner           : zenzh
  6 # AddToMenu       : yes
  7 # Backend         : icinga
  8 # Statetype       : soft
  9 #
10 ###################################
11
12 backnanganmeldeserver = TL01ADS01.TLTGES.local;Hoststatus | TL01ADS01.TLTGES.local;Windows Check Service DNS
13 display 1;backnanganmeldeserver;Backnang Anmeldeserver
14 Dienste = TL02ADS01.TLTGES.local;Windows Check Service DHCP & TL02ADS01.TLTGES.local;Windows Check Service DHCP All Pools & TL02ADS01.TLTGES.local;Windows Check Service DNS
15 display 0;Dienste;Dienste
16
17 etagenverteiler = EMTEL-TW-EVT21;Hoststatus | EMTEL-TW-EVT22;Hoststatus | EMTEL-TW-EVT31;Hoststatus | EMTEL-TW-EVT32;Hoststatus | EMTEL-TW-EVT41;Hoststatus
18 display 0;etagenverteiler;Etagenverteiler
19
20 hauptverteiler = EMTEL-TW-HVT01;Hoststatus & EMTEL-TW-HVT02;Hoststatus
21 display 0;hauptverteiler;Haupt-Verteiler
22
23 SwitchVerteiler = EMTEL-TW-SVT01;Hoststatus & etagenverteiler & hauptverteiler
24 display 0;SwitchVerteiler;Server Verteiler
25
26 Hardware = | SwitchVerteiler
27 display 0;Hardware;Hardware
28
29 teltow_anmeldeserver = Dienste | Hardware
30 display 1;teltow_anmeldeserver;Teltow Anmeldeserver
31

**Comment by larsengels** [comment]
I also stumbled upon this a few weeks ago and it took me a lot of time to find out how to get this working.

You  need to add "--config $configfile" (without the .conf suffix) to your query:
```
$ sudo icingacli businessprocess check process myProcessName --config myProcessNameConfigFile
Business Process OK: myProcessName
```
So you have to have a */etc/icingaweb2/modules/businessprocess/processes/myProcessNameConfigFile.conf*

**Comment by Fiiti** [comment]
Okay. Any chance to get these Information as a variable in director?
I am using icingacli business for check commands, builded in director.

**Comment by nilmerg** [comment]
The `businessprocess process check` command uses the first process configuration listed by `businessprocess process list` as default. This can be changed with the option `--config <configname>` as detailed by @bsdlme above.

Since this is a configuration issue and probably solved, I'll close this.

**Comment by Den3141** [comment]
> The `businessprocess process check` command uses the first process configuration listed by `businessprocess process list` as default. This can be changed with the option `--config <configname>` as detailed by [@bsdlme](https://github.com/bsdlme) above.
> 
> Since this is a configuration issue and probably solved, I'll close this.

Could this be in the official documentation of icinga Business Process please
