### ISSUE TITLE
Fatal error On creating new Business Process

### ISSUE THREAD

**Issue by kundan123456** [Icinga/icingaweb2-module-businessprocess#196]
**Fatal error: Uncaught TypeError: Argument 1 passed to Icinga\Module\Businessprocess\Renderer\Renderer::setUrl()**

Hi Everyone,

After cloning Business Process module from GIT and completing the setup, once I try to create a new Business Process its throwing error.

## Expected Behavior

It should create the Business Process without any error.

## Current Behavior

It is throwing below error:

`Fatal error: Uncaught TypeError: Argument 1 passed to Icinga\Module\Businessprocess\Renderer\Renderer::setUrl() must be an instance of Icinga\Module\Businessprocess\Web\Url, instance of Icinga\Web\Url given, called in /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php on line 176 and defined in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Renderer/Renderer.php:219 Stack trace: #0 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(176): Icinga\Module\Businessprocess\Renderer\Renderer->setUrl(Object(Icinga\Web\Url)) #1 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(92): Icinga\Module\Businessprocess\Controllers\ProcessController->prepareRenderer(Object(Icinga\Module\Businessprocess\BpConfig), NULL) #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\ProcessController->showAction() #3 /usr/share/php/Icinga/Web/Con in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Renderer/Renderer.php on line 219`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Module version (System - About): v2.1.0
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.8.1-1
* Operating System and version: Linux, Ubuntu 18.04.1 LTS (Bionic Beaver)
* Webserver, PHP versions: PHP7.1

**Comment by nilmerg** [comment]
Hi,

I can't reproduce this, neither with v2.1.0 nor with the master you've must have had when creating this issue.

Please tell me the exact git commit hash with which you're facing this error. If it's the current master, please also share the full URL which is causing it.

**Comment by 2Belette** [comment]
Got almost the same issue with either v2.2.0 (73ad4a2) or v2.1.0 (55d9f1e).

`Fatal error: Uncaught TypeError: Argument 1 passed to Icinga\Module\Businessprocess\Renderer\Renderer::setUrl() must be an instance of Icinga\Module\Businessprocess\Web\Url, instance of Icinga\Web\Url given, called in /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php on line 170 and defined in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Renderer/Renderer.php:270 Stack trace: #0 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(170): Icinga\Module\Businessprocess\Renderer\Renderer->setUrl(Object(Icinga\Web\Url)) #1 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(89): Icinga\Module\Businessprocess\Controllers\ProcessController->prepareRenderer(Object(Icinga\Module\Businessprocess\BpConfig), NULL) #2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\ProcessController->showAction() #3 /usr/share/php/Icinga/Web/Con in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Renderer/Renderer.php`

**Comment by nilmerg** [comment]
I've identified the issue in #221 already. You need to upgrade Icinga Web 2 to the latest version.
