### ISSUE TITLE
Class 'ipl\Html\BaseHtmlElement' not found

### ISSUE THREAD

**Issue by Foxeronie** [Icinga/icingaweb2-module-businessprocess#202]
Hey everyone,

I get this error on the current master when I select Business Process in the navigation:

```
ErrorException in /opt/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Component/Controls.php:7 with message: Class 'ipl\Html\BaseHtmlElement' not found
#0 [internal function]: Icinga\Application\Web->Icinga\Application\{closure}()
#1 {main}
```

 The Problem starts with this commit:

```commit 19ae300aca500ec6ef4076e7e67b68be45165f3c
Author: Johannes Meyer <johannes.meyer@netways.de>
Date:   Thu Jan 17 13:21:46 2019 +0100

lib: Remove all traces of `Icinga\Module\Businessprocess\Html`

refs #130 
```

Best regards,
Patrick

**Comment by HactarofDoom** [comment]
Just installed the module on our test system to run it through it's paces, can confirm the bug.

Running Debian 8 / Icinga Web 2.6.2 / Icinga 2.10.2-1

**Comment by Foxeronie** [comment]
Thanks, it's working again with IPL module installed.

**Comment by HactarofDoom** [comment]
Perfect all working, thanks for the update @dnsmichi !

**Comment by mactac27** [comment]
Hey Guys, 
I am facing the same issue however the installation of IPL did not solve the problem. 
Uncaught Error: Class 'ipl\Html\BaseHtmlElement' not found in /usr/share/icingaweb2/modules/reporting/library/vendor/ipl/web/src/Widget/Controls.php
My current setup is:
Icinga Web 2 Version: 2.6.2
I.P.L Version: 0.5.0
Reactbundle Version: 0.9.0
Reporting Version: 0.10.0
PDFexport Version: 0.9.1
