### ISSUE TITLE
breadcrumbs look bad in dark theme

### ISSUE THREAD

**Issue by slalomsk8er** [Icinga/icingaweb2-module-businessprocess#217]
The new breadcrumb style looks bad with a dark theme like solarized-dark.

## Expected Behavior
Arrows get the color from the icingaweb2 theme.

## Current Behavior
![businessprocesses breadcrumb problem](https://user-images.githubusercontent.com/100971/53574305-a2c8fb80-3b6f-11e9-80f0-78848bba7c3e.png)

## Steps to Reproduce (for bugs)
Switch to solarized-dark in your personal icingaweb2 settings.

**Comment by nilmerg** [comment]
Thanks for the report! I wouldn't have noticed this, to be honest.
