### ISSUE TITLE
Business Process check fails, but check works in IcingaWeb2

### ISSUE THREAD

**Issue by FiggyRoll** [Icinga/icingaweb2-module-businessprocess#220]
## Expected Behavior
Business Process check should show green as the check command is returning OK. This is an SNMP check using the centreon plugin, checking the CPU status of a Windows VM.

## Current Behavior
When I add the service to the business process, it initially displays a green tile, however, as soon as I save the configuration the tile turns grey, and a message appears at the top of the business process stating missing nodes.

If i then click the grey tile, it shows the service as OK, but when I click 'check now' the plugin gives the following error

**icinga2: Can't send external Icinga command: 404 No objects found.**

_#0 /usr/share/icingaweb2/modules/monitoring/application/forms/Command/Object/CheckNowCommandForm.php(70): Icinga\Module\Monitoring\Command\Transport\CommandTransport->send(Object(Icinga\Module\Monitoring\Command\Object\ScheduleServiceCheckCommand))
#1 /usr/share/php/Icinga/Web/Form.php(1158): Icinga\Module\Monitoring\Forms\Command\Object\CheckNowCommandForm->onSuccess()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(275): Icinga\Web\Form->handleRequest()
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Web/Controller/MonitoredObjectController.php(60): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->setupQuickActionForms()
#4 /usr/share/icingaweb2/modules/monitoring/application/controllers/ServiceController.php(66): Icinga\Module\Monitoring\Web\Controller\MonitoredObjectController->showAction()
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Monitoring\Controllers\ServiceController->showAction()
#6 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch(String)
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#8 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#9 /usr/share/php/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#10 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#11 {main}_

If I select the service in the normal Icinga Web 2 UI, the service is OK and when I click check now, the check completes successfully.

The normal log file just shows an API the same API call for both scenarios, and I cant see any errors in the debug logs.

## Steps to Reproduce (for bugs)

1.  Monitor a host using the following centreon plugin - os::windows::snmp::plugin
2. The error occurs for CPU, Memory or Disk checks
3. Create a business process and add a service monitored using the module above
4. It will initially show a green tile, save the config and it will turn grey
5. Attempt to run check now, on the service from within the business process and you get a failure message.

It's worth noting that all other services that we have in business processes are working fine, including other centreon plugins.

## Context

This helps with our dashboard, and at a glance monitoring. Unfortunately this error means we have to check the process to ensure it is all working rather than just rely on the tile.

## Your Environment

* Module version (System - About):
    businessprocess | 2.1.0

* Icinga Web 2 version and modules (System - About):
    2.6.1

* Icinga 2 version (`icinga2 --version`):
    icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.0-1)

* Operating System and version:
    System information:
     Platform: Red Hat Enterprise Linux Server
     Platform version: 7.4 (Maipo)
     Kernel: Linux
     Kernel version: 3.10.0-693.11.6.el7.x86_64
     Architecture: x86_64

* Webserver, PHP versions:
    PHP 5.4.16

**Comment by nilmerg** [comment]
Hi,

any chance you give the current master a try? (Note the new dependency on https://github.com/Icinga/icingaweb2-module-ipl)

How you'll navigate to a service's detail view where the `Check Now` link is located makes no difference. In both cases the monitoring module is responsible.
Though, the fact that `Check Now` also shows a problem may indicate that the issue is not with either web application.

If you've got a cluster of Icinga 2 instances, I'd suggest to head over to the [core's issue tracker](https://github.com/Icinga/icinga2/issues). There may be a problem with the synchronization.

**Comment by FiggyRoll** [comment]
Hi @nilmerg 

Thanks for taking a look, tried with the master branch but still the same issue (already have the IPL module from installing the certificate module).

It's interesting, if I add the service to the business process, before clicking 'store' the check shows a green tile, and the 'check now' button also shows the correct result. As soon as I click the 'store' button, thats when it changes to a grey tile, and the 'check now' button produces the error at the top of this thread

**Comment by nilmerg** [comment]
Thanks for the screenshots. Though I'm still not convinced that this is some sort of bug.

a) The businessprocess module retrieves hosts and services from the IDO (database)
b) The check now feature is part of the monitoring module and issues an api request directly to Icinga 2 (daemon)

You say you've got no cluster. Well, but maybe a staging and production setup?
Is it possible that your business process configuration is using a different backend than the monitoring module?

Is load balancing involved? If so, make sure everything is in sync.

**Comment by FiggyRoll** [comment]
Hi @nilmerg 

No cluster, no staging setup. 1 server with all the config. Trying to keep everything as simple as possible until we fully understand how it all works (everything is great so far, just this error for the BP module)

BP is using the default backend, and I haven't configured any other backends. All other BP's work fine, its just this one that is generating the error.

a) The businessprocess module retrieves hosts and services from the IDO (database)
          And this appears to work perfectly before I click the store button, the BP shows as green until and the check now works, until that 'store' button is clicked.

b) The check now feature is part of the monitoring module and issues an api request directly to Icinga 2 (daemon)
           Yep I can see this in the logs, it's doing the exact same API call regardless of whether it is called from the main web module, or from the BP.

What is different once that 'store' button is clicked? It could be to do with the centreon plugin that I'm using, but I am using other centreon plugins which work fine with the BP.

Is there any other logging I can look at? Debug logging didnt appear to show much more info, except more detail around the API call happening

Thanks

**Comment by nilmerg** [comment]
Sorry, I'm out of ideas now. I just tried it myself with this service and it works well.

Please head over to our [forum](https://community.icinga.com/). There are more people active to assist you in locating the issue.
