### ISSUE TITLE
Detail view broken in 2.2.0

### ISSUE THREAD

**Issue by bsdlme** [Icinga/icingaweb2-module-businessprocess#221]
I upgraded from 2.1.0 to 2.2.0, installed the IPL module first and activated both.
We have several business processes defined and the overview is shown correctly.
However if I click on  a business process I am getting this PHP error message:

```
Argument 1 passed to Icinga\Module\Businessprocess\Renderer\Renderer::setUrl() must be an instance of Icinga\Module\Businessprocess\Web\Url, instance of Icinga\Web\Url given, called in /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php on line 170 and defined

#0 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Renderer/Renderer.php(270): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(4096, 'Argument 1 pass...', '/usr/share/icin...', 270, Array)
#1 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(170): Icinga\Module\Businessprocess\Renderer\Renderer->setUrl(Object(Icinga\Web\Url))
#2 /usr/share/icingaweb2/modules/businessprocess/application/controllers/ProcessController.php(89): Icinga\Module\Businessprocess\Controllers\ProcessController->prepareRenderer(Object(Icinga\Module\Businessprocess\BpConfig), NULL)
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\ProcessController->showAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('showAction')
#5 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#6 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#7 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#9 {main}
````
## Your Environment

* Module version (System - About): 2.2.0
* Icinga Web 2 version and modules (System - About): 2.4.2
* Icinga 2 version (`icinga2 --version`): r2.10.2-1
* Operating System and version: Ubuntu 14.04
* Webserver, PHP versions: Apache, PHP 5.5.9

**Comment by nilmerg** [comment]
Hi,

which url is this you've clicked on? What's in the address bar once this error appears?

**Comment by bsdlme** [comment]
The url is https://servername/icingaweb2/businessprocess/process/show?config=eko

**Comment by nilmerg** [comment]
Did something else change? Is this a custom installation of some kind?

I don't think this an issue on our side because that's a rather standard URL. You may get rid of this by purging the entire installation of the module first and then doing a fresh installation of v2.2.0.

**Comment by bsdlme** [comment]
That's what I did. I removed the old businessprocess module directory and extracted the 2.2.0 version. It's not a custom installation. icingaweb2 was installed from packages from packages.icinga.com

**Comment by nilmerg** [comment]
Well, took another look at your environment details. You have Icinga Web 2.4.2 installed. The minimum required version for this module is v2.5.1. Please upgrade your Icinga Web2 installation and this issue is gone.
