### ISSUE TITLE
Possibility to cleanup orphaned nodes

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-businessprocess#222]
## Expected Behavior
Having a button to delete all deleted services and hosts in one step.

## Current Behavior
You have to delete all deleted services and hosts one by one.

## Context
Hosts and services get deleted, but they are still part of the businessprocesses. While you can easily recognize by the color which ones are to be deleted, you have to delete them one by one which can be at least time-consuming. Making this a one-click action, makes maintenance of businessprocesses more easy.

ref/NC/590017

**Comment by nilmerg** [comment]
Hi Dirk,

to which part of the UI are you referring to? Does removing a process node not also remove its children? Do you want to remove multiple children at once by being able to mark/select them?

**Comment by dgoetz** [comment]
Let us take the vagrant box as example because I have not gotten a real life example. In the vagrant box you have a businessprocess "all" and let us assume on the mysql servers the process "bp-mysql-open-files" and the webserver "c1-web-1" gets deleted. In this case it would be possible to delete the Businessprocesses "c1-web-1-web"  and "c1-web-1-mysql" everything about of the host would be gone and for the services you would need to delete "c1-mysql-1: bp-mysql-open-files" from "c1-mysql-1-mysql" and "c2-mysql-2: bp-mysql-open-files" from "c2-mysql-2-mysql". 

So it is about making this easier, so selecting multiple children and than deleting it would be one option and at least in tree view a good one. 

Another option I could think of would be a button next to "Add node" like "Delete deleted objects" which would also work in tree and tile view.

I hope this explains it better.

**Comment by nilmerg** [comment]
Ah, wait, when you're talking about deleted services/hosts you mean they're removed from the monitoring entirely? Missing nodes? And you want something like a *cleanup everything* button which purges all *missing* children and process nodes?

**Comment by dgoetz** [comment]
Yes, removed from the monitoring, and yes, cleanup everything button sounds like a good phrase for it.
