### ISSUE TITLE
Typo in children count

### ISSUE THREAD

**Issue by lx183** [Icinga/icingaweb2-module-businessprocess#223]
## Expected Behavior

If tile has one child, the german version should display 1 Kind.
## Current Behavior

1 Kinder is displayed
## Possible Solution

If count is 1 changed displayed string to Kind.
## Steps to Reproduce (for bugs)

1. Create tile with one child
2. Set language to german

## Your Environment

Business Process Version 2.2.0

**Comment by nilmerg** [comment]
I'll close this in favor of #224. This needs to be touched there anyway.
