### ISSUE TITLE
 vsprintf(): Too few arguments

### ISSUE THREAD

**Issue by UweOhse** [Icinga/icingaweb2-module-businessprocess#234]
## Describe the bug
howAction() in icingaweb2/modules/businessprocess/application/controllers/ProcessController.php
calls 

    $bp->addError(sprintf('There are %d missing nodes: %s', $count, implode(', ', $missing)));

addError calls vsprintf on the result of the sprintf. This fails if some element in $missing contains a % character ("RAM usage in %" check?).

It's impossible to edit / view / work on the business process from then on.

## To Reproduce

1. add some service checks with % in the name ("CPU %").
2. put them into a business process.
3. delete the service check / service.

## Your Environment
icingaweb2 - 2.6.3-1.stretch, icingaweb2-module-businessprocess 2.1.0.

## Fix
Change

            $bp->addError(sprintf('There are %d missing nodes: %s', $count, implode(', ', $missing)));

to

            $bp->addError('There are %d missing nodes: %s', $count, implode(', ', $missing));

in line 114 of

            icingaweb2/modules/businessprocess/application/controllers/ProcessController.php

**Comment by nilmerg** [comment]
Hi,

you're right, thanks for the report. Would you mind opening a PR since you already identified the fix?

**Comment by UweOhse** [comment]
Done. 3 single patches, the first fixes this issue only.
The second goes through all other suspicious addError-Calls.
The third does the same for warn().

./library/Businessprocess/Web/Controller.php has vsprintf in setTitle() and addTitle(). Do the calls to them  need to be guarded against %-characters, too?
