### ISSUE TITLE
more detail informations ob failing services in BP-Service-Check

### ISSUE THREAD

**Issue by robertkrenn** [Icinga/icingaweb2-module-businessprocess#236]
Yet in the detail Output of the BP-service-check only the state of the BP itself is kept. So after the original failed service returned to OK state, the history information of the BP-service-check some kind of useless.
It would be really great if in the BP output the failing services/hosts were mentioned (with their own state) so you can get more information out of it, even if the problem itself has already been resolved.

**Comment by nilmerg** [comment]
Hi, the command allows to pass it the `--details` switch which will list all children with problems at the time of the check. There also their host is shown.
