### ISSUE TITLE
Include indicator for Downtime/ACK in TileRenderer

### ISSUE THREAD

**Issue by Olaf-Kueppers** [Icinga/icingaweb2-module-businessprocess#237]
When looking at a given process with the tree view, the individual nodes reflect whether or not an Acknowledgement/Downtime is set on the leafs (which is also inherited through the tree when all leaves share the same status).

Please also include these indicators into the TileRenderer to allow for instant determintation whether or not a process needs attention.

**Comment by nilmerg** [comment]
Hi, isn't this the case? At least somehow, as a tile gets the brighter less saturated state color to show it as *handled*. The tree view only got an icon for this because the color is not that prominent there.

**Comment by Olaf-Kueppers** [comment]
Hi, that seems to be my bad since i havent been aware of that subtle difference in tile coloring.
If this request might mean a lot of effort I would have to resort to look at the tiles more closely (yet, if there is no reference tile that has the “handled” tone, one cloud easily be tricked into believing that everything is handled…? So from that point of view I would really appreciate a little icon reflecting ACK/Downtime).

Kind regards
Olaf Küppers

**Comment by nilmerg** [comment]
Well, no. That's not much effort, I guess. Just relying on the color is also not that *reliable* :thinking: . An additional icon won't hurt here.
