### ISSUE TITLE
Show critical count in the left menu if a BP is critical

### ISSUE THREAD

**Issue by NeverUsedID** [Icinga/icingaweb2-module-businessprocess#246]
# Describe the solution you'd like

![image](https://user-images.githubusercontent.com/7545210/66390771-a5c08000-e9cb-11e9-81db-289d74145795.png)

As shown in the image, I would like to see a marker on the menu item, if a businessprocess is critical

Thanks for this great module. I realy like it a lot :)

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll consider this feature for one of our next releases.

All the best,
Eric

**Comment by lippserd** [comment]
Merged in #340
