### ISSUE TITLE
Make the usage of dropdown-fields in businessprocess forms optional

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingaweb2-module-businessprocess#250]
## Is your feature request related to a problem? Please describe.
Hello,

we have about 20.000 hosts in our icinga. When I try to edit a business process item via GUI, the amount of hosts in the resulting dropdown-form almost kills the browser and makes it unresponsive for a few seconds. This is uncomfortable.

## Describe the solution you'd like
Can you make the use of dropdown-forms optional (eg. with a checkbox) and check the form-content afterwards?

**Comment by nilmerg** [comment]
Hi.

No, validating the host name afterwards would then require everyone to know exactly how hostnames are written.

We'd want to add auto-completion instead: #30. Please leave your feedback there.
