### ISSUE TITLE
Possibility to sort nodes temporarily different

### ISSUE THREAD

**Issue by svamberg** [Icinga/icingaweb2-module-businessprocess#252]
I used BP over all network devices (400+ switches, 700+ AP, ...), it's not easy find one of failed device. You must scroll over very long page.

Default order by name is good solution, but better is ordering by severity and then by name.

**Comment by lippserd** [comment]
Hi,

Thanks for the report. We'll consider this feature for one of our next releases.

All the best,
Eric
