### ISSUE TITLE
Document operator evaluation

### ISSUE THREAD

**Issue by riban-bw** [Icinga/icingaweb2-module-businessprocess#259]
## Describe the bug
A node configured with operator OR seems to logical AND results. 
A node configured with operator AND seems to logical OR results

## To Reproduce

1. Configure a node as OR
2. Add several services to node
3. Set a node to fail state

## Expected behavior
If any services is in fail state, node shows fail state, i.e. service 1 OR service 2 OR service 3 fails.

## Actual Behaviour
If all services are in fail state, node shows fail state, i.e. service 1 AND service 2 AND service 3 fails.

## Additional context
Converse behaviour for AND operator, i.e. any service fail will trigger node to show failed.
Maybe developer had inverted logical approach, i.e. logic operates on OK state - service 1 OR service 2 OR service 3 is OK. This is not intuitive to me. I do not see documentation describing this logic.

**Comment by nmartinii** [comment]
Our operators use the OK or UP status to determine the result. That means, in case of the OR operator, a node is OK as long as at least one subnode is OK/UP. The AND operator, on the other hand, expects all sub-nodes to be OK/UP.
Though, we'll update our documentation to make it more clear how a node's state is calculated.

**Comment by nmartinii** [comment]
Our operators use the OK or UP status to determine the result. That means, in case of the OR operator, a node is OK as long as at least one subnode is OK/UP. The AND operator, on the other hand, expects all sub-nodes to be OK/UP.
Though, we'll update our documentation to make it more clear how a node's state is calculated.
