### ISSUE TITLE
Ability to rename node

### ISSUE THREAD

**Issue by riban-bw** [Icinga/icingaweb2-module-businessprocess#260]
There may be errors during configuration of nodes. A node may have inappropriate name. The node name cannot be changed and rebuilding configuration may require much effort.

## Describe the solution you'd like
It would be advantageous to be able to rename a node in the node edit mode.

## Describe alternatives you've considered
Replacing nice with s new instance is not possible because there does not seem to be a way to add existing child nodes to the new node.

## Additional context
There may be constraints where a node is referenced elsewhere but renaming is not possible even if this is not the case. Also other references configuration can be removed resulting in errors in UI so similar behaviour seems acceptable.

**Comment by lippserd** [comment]
Hi @riban-bw,

We distinguish between ID and display name. ID is used in the configuration files for referencing/importing nodes and display name for the view.

It is possible to change the display name at any time. Isn't that sufficient?

All the best,
Eric

**Comment by nilmerg** [comment]
Changing the display name works fine. If the host/service name changes, it can be removed and re-added.
