### ISSUE TITLE
[dev.icinga.com #9713] Notifications for Business Processes

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#27]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9713

**Created by jgruber on 2015-07-23 06:54:48 +00:00**

Assignee: _jgruber_
Status: _Closed_  (closed on _2016-11-23 16:51:05 +00:00_)
Target Version: _(none)_
Last Update: _2016-11-23 16:51:05 +00:00 (in Redmine)_

---

A business processes that fail should trigger a notification like a failed service or host does. Same functionality as in Nagios Business Process Addon would be sufficient and great to have with this module.

**Comment by swizzly** [comment]
Hi,
for me  the CLI command does not work:
`
$ icingacli businessprocess process list
MyBusinessProcess (mybp)
$ icingacli businessprocess check process mybp
ERROR: Exception in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php:518 with message: The node "mybp" doesn't exist
$ icingacli businessprocess check process MyBusinessProcess
ERROR: Exception in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php:518 with message: The node "MyBusinessProcess" doesn't exist
`
What's wrong?

**Comment by Thomas-Gelf** [comment]
Hi @swizzly!

    $ icingacli businessprocess process list
    MyBusinessProcess (mybp)

This shows that you have a single configuration file, `mybp`. You can show the processes available in that file with:

    $ icingacli businessprocess process list mybp

You need to pass process names to your check command, I guess there is no node named `mybp`. And as sooner or later there might be more configuration files that just `mybp`, I'd strongly suggest to always pass `--config`:

```
# icingacli businessprocess process check --help
Check a specific process
========================

USAGE

icingacli businessprocess process check <process> [options]

OPTIONS

  --config <configname>   Name of the config that contains <process>
  --details               Show problem details as a tree
  --colors                Show colored output
  --state-type <type>     Define which state type to look at. Could be
                          either soft or hard, overrides an eventually
                          configured default
```

Cheers,
Thomas

NB: Please open dedicated issues for new problems, I do not see how this should be related to 'Notifications for ...', been closed 4 month ago

**Comment by addyaddy22** [comment]
@Thomas-Gelf im having the same issue,i have created my business [process but i cant figure out how to trigger a notification when the business profile goes down, kindly assist
