### ISSUE TITLE
Fetch business processes and their current state from an API

### ISSUE THREAD

**Issue by StreatCodes** [Icinga/icingaweb2-module-businessprocess#284]
Hi,

## Is your feature request related to a problem? Please describe.
We would like to provide insight into business processes outside of the IcingaWeb interface. 

## Describe the solution you'd like
I had a quick look through the source code of this module and I couldn't see any way to get a list of business processes or their current state through an API. It looks like the business process configuration is in a custom format saved on the file system, is their a way to get this information as JSON? or some other serialized format?

Are there any plans to add a feature like this in the near future? If not, would you be interested in accepting a pull request which provides this functionality?

Thanks for developing and open sourcing this great module!

**Comment by davekempe** [comment]
I second this. We have an exciting new project we are working on and being able to source the Business Processes themselves via an API could be super handy.

**Comment by Kotove** [comment]
you can try JSON export feature:
https://github.com/Icinga/icingaweb2-module-businessprocess/pull/180

**Comment by xFuture603** [comment]
Any movement on this topic? Would also be interested to use this great module with an API!

**Comment by nilmerg** [comment]
As already mentioned, the process views are all exportable now. I consider this solved.
