### ISSUE TITLE
Audit Log

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-businessprocess#289]
## Is your feature request related to a problem? Please describe.

We need a way to track who is changing what in Business Processes via webinterface. We can make sure that users don't have access to the configuration files or database information but right now we can't track user activity for web users.

It would be great to have this functionality integrated with a global audit log of Icinga Web 2 where other modules could hook on, too.

## Describe the solution you'd like

I'd like to have information about changes in the Business Process configuration to be tracked via Icinga Web 2 audit log.

A separate log file would be fine but a combined approach would be much more useful.

At least `username`, `object name`, `type of change` and `timestamp` should be included.

## Describe alternatives you've considered
None.

## Additional context
ref/NC/702008

**Comment by widhalmt** [comment]
I'd say, yes. That's enough for a start. If someone needs more features, that would be another issue if you ask me.

**Comment by nilmerg** [comment]
Okay, I'll close here then.
