### ISSUE TITLE
[dev.icinga.com #9821] BP / Modify this process / cant change name

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#29]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9821

**Created by ClemensBW on 2015-08-03 17:47:34 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2017-01-11 16:50:22 +00:00 (in Redmine)_

---

Hi,

if want in BP to "Modify this process" i can change every field, but not the "Name".

regards,
Clemens

**Attachments**

* [BP_name_field.png](https://dev.icinga.com/attachments/download/2598/BP_name_field.png) ClemensBW - _2015-08-03 17:47:26 +00:00_

**Comment by nilmerg** [comment]
If interested, please create a new issue.
