### ISSUE TITLE
Don't allow deletion of referenced processes

### ISSUE THREAD

**Issue by EmmaTinten** [Icinga/icingaweb2-module-businessprocess#296]
Deleting a process which is an element of another process should not be possible. If this happens the Web UI is no more usable, someone must create the empty process.

Version is 2.3.0 of businessprocess.

**Comment by nilmerg** [comment]
Just tried this myself using the current master and I can't reproduce that. No matter which one of the two removal types I choose, the config is correctly updated and there's no trace left of the process I remove.

Please provide a detailed step by step instruction how you can reproduce that.

**Comment by EmmaTinten** [comment]
I'll give you a description:

1. create a business process which contains at least one service
2. create another business process which only contains the previously created process
3. check the processes, they will be o.k.
4. remove the process you created in step 1
5. try to access the ui

Editing the config files below works or just restoring the previously deleted. I expect a check prior deleting something that this is not in use by other processes.

**Comment by nilmerg** [comment]
Still can't reproduce. Performing your steps gives me the following without saving:

![Screenshot from 2021-06-02 11-54-53](https://user-images.githubusercontent.com/16668527/120460762-b2ac9700-c399-11eb-9cf2-0baf8cb3fa7c.png)

and this with saving first before I remove "One":

![Screenshot from 2021-06-02 11-56-20](https://user-images.githubusercontent.com/16668527/120460786-b6d8b480-c399-11eb-97cf-4ed5224e80bc.png)

Also doing a final save in both situations still keeps the UI working fine.

**Comment by EmmaTinten** [comment]
test.conf out of /etc/icingaweb2/modules/businessprocess/processes/

```
### Business Process Config File ###
#
# Owner           : icingaadmin
# AddToMenu       : yes
# Statetype       : soft
#
###################################

testnode = icinga-master.vrc.lan;http
display 1;testnode;testnode
```

testdep.conf, secondary defintion:

```
### Business Process Config File ###
#
# Owner           : icingaadmin
# AddToMenu       : yes
# Statetype       : soft
#
###################################

testdepnode = @test:testnode
display 1;testdepnode;testdepnode
```


There must be two processes, one including the other. When this is configured, remove the included process.

Is this sufficient?

**Comment by nilmerg** [comment]
Aaaah, a reference between entire configurations, not just between processes. :bulb: 

Reproduce it now. Thanks for the clarification.
