### ISSUE TITLE
When pulling the latest version 2.3.1 it still shows as version 2.3.0 in Icingaweb2

### ISSUE THREAD

**Issue by agougo** [Icinga/icingaweb2-module-businessprocess#299]
## Describe the bug
When pulling version 2.3.1 it installs correctly but it shows as version 2.3.0 in Icingaweb2

## To Reproduce
https://HOSTIP/icingaweb2/about

1. Go to the above URL
2. See the module versions

## Expected behavior
The module should show as version 2.3.1

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.9.0
* Web browser used: Firefox 90.0.2
* Icinga 2 version used (`icinga2 --version`): 2.12.5
* PHP version used (`php --version`): 7.3.20
* Server operating system and version: Oracle Linux 8.4

**Comment by nilmerg** [comment]
In the tagged commit, the `module.info` file has the proper version. Did you pull the master by chance?

**Comment by agougo** [comment]
Oh yes, i pulled the master :(

I corrected my command line to look like this and now it works properly. Apologies for the hustle.

ICINGAWEB_MODULEPATH="/usr/share/icingaweb2/modules"
REPO_URL="https://github.com/Icinga/icingaweb2-module-businessprocess"
TARGET_DIR="${ICINGAWEB_MODULEPATH}/businessprocess"
MODULE_VERSION="2.3.1"
 
git clone "${REPO_URL}" "${TARGET_DIR}" --branch v${MODULE_VERSION}
