### ISSUE TITLE
[dev.icinga.com #9822] BP / add autocomplete

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#30]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/9822

**Created by ClemensBW on 2015-08-03 18:51:31 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _Backlog_
Last Update: _2016-11-29 14:23:48 +00:00 (in Redmine)_

---

Hey,

please add a autocomplete option for new hosts / nodes. \[1\]
With a few thousand, needs several time to scroll down ;o)

\[1\]/icingaweb2/businessprocess/node/add?config=$foo

regards,
Clemens

---

**Relations**:

* relates [#11059](https://dev.icinga.com/issues/11059)

**Comment by K0nne** [comment]
Hi! I have a similar problem. With several thousand hosts editing of a node is very uncomfortable, because every keystroke renders the browser useless for a few seconds.

**Comment by nilmerg** [comment]
Duplicate of #295
