### ISSUE TITLE
You are lacking permission to access service

### ISSUE THREAD

**Issue by bisontim** [Icinga/icingaweb2-module-businessprocess#304]
Hallo.
I added a service to Business processes, but, when I Store, I obtain:

You are lacking permission to access service “…”

I only use UI to create Business Process node.

How could I investigate on this?
What is the problem?
Thanks a lot
Mario

icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.1-1)

Icinga Web 2 Version
2.9.3
Git commit
c757a17530c326c7d6daebd6171486cb8167a8a1
PHP Version
7.2.24-0ubuntu0.18.04.8
Git commit date
2021-08-10

Modules:
businessprocess 2.3.1
director master
fileshipper 1.1.0
monitoring 2.9.3

**Comment by nilmerg** [comment]
Please don't do cross-posts: https://community.icinga.com/t/business-processes-you-are-lacking-permission-to-access-service/8092
