### ISSUE TITLE
IDs of Business Process Nodes aren't visible in Icingaweb

### ISSUE THREAD

**Issue by Nayakum** [Icinga/icingaweb2-module-businessprocess#308]
It doesn't seem to be possible to see IDs of BP Nodes in Icingaweb post creation. For the ID of a BP itself it's easy.

Business Process --> Config; here, you see both the ID and the Display Name

![grafik](https://user-images.githubusercontent.com/84782250/135452016-6a0fb27d-f960-40b0-980d-a7a91024266a.png)

Business Process Node --> Config: here, you only see the Display Name

![grafik](https://user-images.githubusercontent.com/84782250/135452079-adbe3b2d-8010-485a-a006-8006f3fc7322.png)

This makes the configuration of Services on the basis of Business Processes difficult, since you need the ID of the node to survey. Also, a change of the ID after creation of the Node is not possible, at least not in the web GUI.

We use Icinga Web Version 2.8.2 and our business process module is on Version 2.3.1.
If this is intended, please treat this as more of a "Feature request" than a "Bug report."

Best wishes,
Pascal

**Comment by Nayakum** [comment]
Hello nilmerg, thanks a lot for your reply and correcting the label. This already helps me when setting up monitoring for our Business Processes, and having an easier way in the future is always welcome. :) Aditionally, in case it got lost in my inital post, editting of the IDs in the web GUI would be much appreciated.

Best wishes,
Pascal

**Comment by nilmerg** [comment]
Editing is difficult to implement, as the IDs may be used as references in other configs. So editing an ID requires updates in other configs as well. This should be tackled as part of #11.
