### ISSUE TITLE
Parse Error when adding a node with semicolon in the varname

### ISSUE THREAD

**Issue by Tqnsls** [Icinga/icingaweb2-module-businessprocess#312]
## Describe the bug
A clear and concise description of what the issue is.
One of our colleagues added a new node with a name like "vSAN Nuremberg; Citrix Worker" after saving the config the complete business-config fails and is uneditable anymore over the webbrowser only via console with vim / nano to the file in "/etc/icingaweb2/modules/businessprocess/processes"

Error is like 
<code>Parse error on /etc/icingaweb2/modules/businessprocess/processes/node.conf:<row>: No semicolon allowed in varname</code>

Similar behavior as in https://github.com/Icinga/icingaweb2-module-businessprocess/issues/71 and https://github.com/Icinga/icingaweb2-module-businessprocess/issues/26

## Expected behavior
I can think of several options here, best way was to show an error before saving the config file with something like "nasty character semicolon (for example) was used, please check" or some change of parsing so the website and the business config / node is still editable.
Our colleagues do not have access to the businessmodule director to correct it via text editor themselves.

![image](https://user-images.githubusercontent.com/67681686/143052056-42dddfec-c8c2-4ccc-a073-7ba0140b2ed9.png)

## Your Environment
icingaweb2: v 2.9.3
module businessprocess: v 2.3.0
PHP: v 7.3.29
OS: RHEL 7

**Comment by nilmerg** [comment]
See also #92
