### ISSUE TITLE
Status indicators of handled checks are display without colour in tree view

### ISSUE THREAD

**Issue by log1-c** [Icinga/icingaweb2-module-businessprocess#318]
## Describe the bug
Status indicators of handled checks are displayed without colour in the tree view of a BP.
Only critical checks are displayed correctly

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Create BP
2. Create (or simulate) a downtime/ack
3. check will be displayed without color once switched to tree view

## Expected behavior
Status indicator shows the correct color depending on the state.
## Screenshots
_OK handled_
![image](https://user-images.githubusercontent.com/24474580/151384467-382a5a29-a727-4795-8a09-f9836f5ff507.png)
_Warning handled_
![image](https://user-images.githubusercontent.com/24474580/151384489-985211a2-a064-4486-8e9f-e11bcb28be2c.png)
_Unknown handled_
![image](https://user-images.githubusercontent.com/24474580/151384526-0151d655-5fea-431c-af3d-9cadceb80e6c.png)

only correct one is _Critical handled_
![image](https://user-images.githubusercontent.com/24474580/151384715-06c1ba32-ab03-4f5b-8ea7-e585714cd12f.png)

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.9.5 // BP module v2.3.1
* Web browser used: Edge & Vivaldi (both Chromium)
* Icinga 2 version used (`icinga2 --version`): 2.13.2
* PHP version used (`php --version`): 7.2 & 7.4
* Server operating system and version: RHEL8 & Ubuntu 20.04

**Comment by nilmerg** [comment]
Hi,

thanks for the report, this is already fixed in the master since #309.
