### ISSUE TITLE
Dependencies not available?

### ISSUE THREAD

**Issue by danielmoser96** [Icinga/icingaweb2-module-businessprocess#324]
## Describe the bug
I have installed the latest dependencies. But newer versions are still needed in the module?

icinga-php-library >=0.8.0 (currently installed 0.7.0)
icinga-php-thirdparty >=0.11.0 (currently installed 0.10.0)

- [icinga-php-thirdparty](https://github.com/Icinga/icinga-php-thirdparty/releases) : latest release 0.7.0
- [icinga-php-library](https://github.com/Icinga/icinga-php-library/releases) : latest release 0.10.0

**Comment by nilmerg** [comment]
Yes. Install the nightly branch of each for tests. (https://github.com/Icinga/icinga-php-thirdparty/tree/snapshot/nightly, https://github.com/Icinga/icinga-php-library/tree/snapshot/nightly)
