### ISSUE TITLE
Documentation suggests the installation of 2.2.0

### ISSUE THREAD

**Issue by dreua** [Icinga/icingaweb2-module-businessprocess#327]
The instructions to [install the Business Process Module on icinga.com](https://icinga.com/docs/icinga-business-process-modelling/latest/doc/02-Installation/) lead to the installation of 2.2.0. I think it should be upgraded at least to 2.3.1 which fixes an issue when in use with Icinga Web 2 v2.9.

**Comment by nilmerg** [comment]
@bobapple Please update the website, it's heavily outdated.

**Comment by bobapple** [comment]
Updated the docs to v2.4.0
