### ISSUE TITLE
IcingaDB - Services in BPs are not shown anymore for filtered roles (missing nodes)

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2-module-businessprocess#345]
## Describe the bug
Hi all,
I have two different views between the monitoring and the icingadbweb module right now.
Monitoring: When a role has access to a BP, the user can see the whole BP, no matter if the user has access to the several service details or not. When they don't have access to the service details, they get a permission denied info. But they can see the whole status of the BP itself

IcingaDB: The services, which are locked for the role disappear in the business process, too. The user gets the red bar with "X nodes are missing". So the BP is not usable anymore. I have to unlock every service for the roles, what was not necessary in the monitoring module. 

## To Reproduce

1. Create a BP
2. Filter a service for a specific role
3. The service is visible in the BP for the filtered role when using the monitoring module, service details are locked with "no permission"
4. The service is not visible in the BP for the filtered role, when using the Icingadbweb module, user gets "nodes missing"

## Expected behavior
Same view in both monitoring and icingadbweb modules

## Screenshots
![image](https://user-images.githubusercontent.com/7324088/183825185-ab91204f-8149-4271-83b4-ef836136d9b8.png)
![image](https://user-images.githubusercontent.com/7324088/183825226-916e64b7-9354-4d9b-9dfc-4a146e1bd99c.png)

## Your Environment
Ubuntu 20.04.4 lts
Icinga Web 2 Version	2.11.1
PHP Version	7.4.3
icinga/icinga-php-thirdparty	0.11.0
icinga/icinga-php-library	0.9.1
businessprocess		2.4.0	Configure

## Additional context
Module is currently not usable with IcingaDB :(

**Comment by MarcusCaepio** [comment]
Good morning all,
the PR is open since 19 days. When will it be merged? We really would like to use the module again :)

**Comment by nilmerg** [comment]
It's included in version [2.4.1](https://github.com/Icinga/icingaweb2-module-businessprocess/releases/tag/v2.4.1) released just now.
