### ISSUE TITLE
"Hosts from filter" does not work like expected

### ISSUE THREAD

**Issue by s-blottk** [Icinga/icingaweb2-module-businessprocess#349]
When filtering for a specific hostname like "host_name=AC-CADMN0*" i am expecting the hosts "AC-CADMN01" and "AC-CADMN02" to be selected. But as to be seen in the screenshot, all hosts are displayed in the list.

1. Where is the error in the query?
2. Does this function let you pre-filter and then manually select hosts from the list or does it allow to dynamically add hosts from the query, even whenever hosts are added that apply to this query in the future?

![image](https://user-images.githubusercontent.com/49557314/187959761-114d4177-3d43-433f-bab9-a34c650532b2.png)

**Comment by nilmerg** [comment]
> Where is the error in the query?

The filter is not applied :joy: It also shows a stacktrace instead of a less intrusive error message in case the filter is invalid and Icinga DB is used.

> Does this function let you pre-filter and then manually select hosts from the list

This.

**Comment by s-blottk** [comment]
You mean submitting by pressing "refresh"? 
This doesn't work either. 

Could you provide a example of a filter that actually works?

**Comment by nilmerg** [comment]
Your filter is fine, it should work. I really mean, whatever you define, it's not applied. That's the bug. :wink:
