### ISSUE TITLE
Disable automatic unfolding after manual collapsing

### ISSUE THREAD

**Issue by EmmaTinten** [Icinga/icingaweb2-module-businessprocess#359]
## Describe the bug

Using the tree view button on a node and then collapse a process will unfold the manual unfolded children  after 10-15 seconds. Tested with Chrome and Firefox. This does not occur if you are using the tree view button of the whole process.

## To Reproduce

1. Create a process
2. Define some twigs in the tree view
3. Go to BPM overview
4. Use the tree view button on a node
5. Unfold services
6. wait 10~15 seconds

## Screenshots

![image](https://user-images.githubusercontent.com/45063741/193248760-7136397a-34b2-4bb9-8953-da7bd76e44c5.png)

The tree view button on the node view behaves different than the tree view button of the whole process.

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.11.1
  businessprocess:  2.3.1
* Web browser used: Chrome, Firefox
* Icinga 2 version used (`icinga2 --version`):  r2.13.5-1
* PHP version used (`php --version`): 7.3.31-1~deb10u1
* Server operating system and version: Debian

**Comment by sukhwinder33445** [comment]
Fixed with https://github.com/Icinga/icingaweb2-module-businessprocess/pull/336
