### ISSUE TITLE
One missconfigured BPM fails all other BPMs too

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingaweb2-module-businessprocess#370]
## Describe the bug
If there is one missconfigured (aka manualy edited BPM), the module will only thow an error that the BPM cant be read and does not work for all others anymore.

## To Reproduce

1. Create some BPMs and then edit one with false configuration in it
2. Open Icingaweb and navigate to BPM module

## Expected behavior
Error message which BPM can't be loaded and display the working ones

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 
 ```
Icinga Web 2  2.11.4
Git Commit    11453bfa92a70a44efbf7f966f5e7f27e9300a28
PHP Version   8.1.2-1ubuntu2.11
MODULE           VERSION
businessprocess  2.4.0
icingadb         1.0.2
cube             1.3.0
director         1.10.2
doc              2.11.4
grafana          2.0.1
incubator        0.20.0
interfacetable   0.0.1
nagvis           1.1.1
pdfexport        0.10.2
reporting        0.10.0
```
* Web browser used: Firefox, Chrome, Edge, Netscape
* Icinga 2 version used (`icinga2 --version`): 2.13.7
* PHP version used (`php --version`): 8.1.2
* Server operating system and version: Ubuntu 22.04

**Comment by slalomsk8er** [comment]
Is this true if the BPs are in the same ini file or does you see the problem over multiple files?

**Comment by Mikesch-mp** [comment]
In my case it was multiple files. One got edited and was faulty.

**Comment by sukhwinder33445** [comment]
Hi @Mikesch-mp,

what kind of misconfiguration do you mean? Can you please explain the steps to reproduce with a concrete example. 

Thanks

**Comment by Mikesch-mp** [comment]
Use whatever breaks the configuration like double ';' or double '&' for example.

**Comment by sukhwinder33445** [comment]
Do you mean an error message like in the screenshot below? 

I just added a `;` to `mysecond` config file, but the other configs still work, in my case the `main` still works properly.

<img width="1032" alt="Screenshot 2023-06-09 at 09 10 27" src="https://github.com/Icinga/icingaweb2-module-businessprocess/assets/54990055/48c2f6b5-fe91-45d3-9652-56ca53d8cc41">

**Comment by Mikesch-mp** [comment]
It works if you have them added to Menu, which is limited. If you have hundreds of BPMs, all the others are not accessible if you dont know the name and edit your URL. If there is a faulty BPM config file, it should be ignnored or marked as faulty like when a Node is missing in a BPM, but not block access to all the others BPMs

**Comment by sukhwinder33445** [comment]
Hi @Mikesch-mp,

can you please test the linked PR ?

Thanks

**Comment by Mikesch-mp** [comment]
I will try it over the weekend. today iam too busy with Windows :(
