### ISSUE TITLE
New official 2.4.1 / 2.5.0 release?

### ISSUE THREAD

**Issue by Tontonitch** [Icinga/icingaweb2-module-businessprocess#371]
Hello,
As the version 2.4.0 of the module has been released more than 1 year ago, and is not really compatible with icingadb, could an official version 2.4.1 be released (or 2.5.0), including the fixes / commits related to the 14 issues already closed and currently part of the milestone 2.5.0?
So we would have a version of the plugin officially compatible with icingadb (fixing issues like #345 ).
Thanks,
BR

**Comment by sebek72** [comment]
An updated release would be great. All my old BP configs are broken with the newest icingaweb2 + icinga-db.

**Comment by adaevitncar** [comment]
It would be great!

**Comment by nilmerg** [comment]
v2.5.0 is somewhat imminent

**Comment by nilmerg** [comment]
[v2.4.1](https://github.com/Icinga/icingaweb2-module-businessprocess/releases/tag/v2.4.1) even more
