### ISSUE TITLE
Error uploading a Business Process Config File

### ISSUE THREAD

**Issue by bisontim** [Icinga/icingaweb2-module-businessprocess#377]
Hi, I am trying to upload a config file.
I obtain: Uninitialized string offset: 0

![image](https://github.com/Icinga/icingaweb2-module-businessprocess/assets/3798487/f26a88bf-af88-44b6-8258-db2312912a60)

Icinga Web 2 Version 2.11.4
Git commit 11453bfa92a70a44efbf7f966f5e7f27e9300a28
PHP Version 7.4.3-4ubuntu2.18
Git commit date 2023-01-26

icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.7-1)

Loaded Libraries
icinga/icinga-php-thirdparty 0.11.0
icinga/icinga-php-library 0.12.0
Loaded Modules
businessprocess 2.4.0
director 1.10.2
fileshipper 1.2.0
graphite 1.1.0
incubator 0.20.0
monitoring 2.11.4

OS="Ubuntu" VERSION="20.04.6 LTS (Focal Fossa)"

Server version: Apache/2.4.41 (Ubuntu)
Server built: 2023-03-08T17:32:54

PHP 7.4.3-4ubuntu2.18 (cli) (built: Feb 23 2023 12:43:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
with Zend OPcache v7.4.3-4ubuntu2.18, Copyright (c), by Zend Technologies

**Comment by nilmerg** [comment]
The configuration you're trying to upload would be most helpful in this case ;)
