### ISSUE TITLE
[dev.icinga.com #10494] Use Host/Service group objects as source data for hosts and services in process definitions

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#38]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/10494

**Created by ziaunys on 2015-10-29 18:29:36 +00:00**

Assignee: _ziaunys_
Status: _Feedback_ 
Target Version: _(none)_
Last Update: _2015-12-16 17:45:15 +00:00 (in Redmine)_

---

It would be nice to have the ability to use the Icinga2 host/service objects as source data for host and service definitions instead of having to hard code every host and service. I have a couple different ideas here.

In order to avoid changing the configuration format of the business process module, the logic of mapping host/service groups to actual hosts and services could be handled in the module itself. There's also the possibility of using custom variables on Icinga2 objects to specify which business processes they participate in. Maybe that's just a simple tag that's referenced in the process definition.

Here's a simple example.

Given HostGroup "app1" with hosts "node1", "node2", and "node3"

We can reference the HostGroup in the business process definition like this:

app1 = 2 of: ${HostGroup:app1};http

This syntax isn't great and it doesn't account for logical operations. I would assume that this would translate to:
app1= 2 of: node1;http + node2;http + node3;http

---

**Relations**:

* relates [#8589](https://dev.icinga.com/issues/8589)

**Comment by Thomas-Gelf** [comment]
The linked issue is now #14 on GitHub, closing this one.
