### ISSUE TITLE
PDF export doesn't work

### ISSUE THREAD

**Issue by yhabteab** [Icinga/icingaweb2-module-businessprocess#407]
## Describe the bug

Exporting the views to PDF renders just an empty page.
<img width="1240" alt="Bildschirmfoto 2023-08-15 um 11 40 46" src="https://github.com/Icinga/icingaweb2-module-businessprocess/assets/57616252/cb54d3f8-d5b4-4507-b50a-4ffbf09c40c9">

<img width="1422" alt="Bildschirmfoto 2023-08-15 um 11 39 03" src="https://github.com/Icinga/icingaweb2-module-businessprocess/assets/57616252/98f6b5c9-b00a-42c3-8dfd-a82bc9777ed2">

**Comment by sukhwinder33445** [comment]
Fixed with https://github.com/Icinga/icingaweb2/pull/5084
