### ISSUE TITLE
Error with IcingaDB-Web 1.1.0: Object of class DateTime could not be converted to number

### ISSUE THREAD

**Issue by RafaelSche** [Icinga/icingaweb2-module-businessprocess#411]
## Describe the bug
See Screenshot.

## To Reproduce
Setup an Icinga Server on a Debian Bullseye Machine. Version below.

## Screenshots
![test](https://github.com/Icinga/icingaweb2-module-businessprocess/assets/47508551/34c71913-c5c0-4420-900c-b494ba828f66)

## Your Environment

* Icinga Web 2 version and modules (System - About): 2.12.0
* Web browser used: Mozilla Firefox
* Webserver: Apache2    2.4.56-1~deb11u2
* Icinga 2 version used (`icinga2 --version`): r2.14.0-1
* PHP version used (`php --version`): 7.4.33
* Server operating system and version: Debian 11 Bullseye
* Businessprocess: 2.4.0

**Comment by sukhwinder33445** [comment]
Hi @RafaelSche,

This issue has already been [fixed](https://github.com/Icinga/icingaweb2-module-businessprocess/pull/374). The next version will be released very soon and will include the fix.

**Comment by nilmerg** [comment]
Resolved by #414

**Comment by nilmerg** [comment]
[v2.4.1](https://github.com/Icinga/icingaweb2-module-businessprocess/releases/tag/v2.4.1) is out now, which solves this issue.
