### ISSUE TITLE
Ignore ack, downtime sub-processes in overall node state

### ISSUE THREAD

**Issue by sebek72** [Icinga/icingaweb2-module-businessprocess#428]
## Is your feature request related to a problem? Please describe.
Having multiple sub-processes using AND operator count all nodes and one of them is bad them the main node is also bad. So far so good.

<img width="747" alt="Screenshot 2023-11-18 at 09 04 23" src="https://github.com/Icinga/icingaweb2-module-businessprocess/assets/15362252/38c07b06-1d4d-492a-82a5-604b814f5236">
<img width="930" alt="Screenshot 2023-11-18 at 09 04 16" src="https://github.com/Icinga/icingaweb2-module-businessprocess/assets/15362252/1caa8685-814c-4b0c-8662-08e1ee16e692">

## Describe the solution you'd like
Acknowledged or downtime services should be excluded from the overall status. Since maybe they are disabled and should not contribute to overall state.

**Comment by nilmerg** [comment]
Though, the main node (Recordings, in this case) is also *handled*, as shown in the upper right corner. So there's no oversight on our end. To categorize this request then: It is about a change in design.

**Comment by sebek72** [comment]
Understood. It would sill be cool to have an option to ignore handled states to a main node would be green if all non-handled sub-processes are OK.

**Comment by nilmerg** [comment]
Upon further analysis, this turned out to be a bug. The icon is there, yeah, but the color should change as well, which it doesn't.
