### ISSUE TITLE
Obscure error message after migration to icingadb when config is older

### ISSUE THREAD

**Issue by RincewindsHat** [Icinga/icingaweb2-module-businessprocess#430]
## Describe the bug
After switching to IcingaDB adding new nodes (and possibly other actions) does result in the error message:

```
Too few arguments to function ipl\Sql\Connection::select(), 0 passed in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/State/MonitoringState.php on line 73 and exactly 1 expected
```

If the line
```
# Backend: icinga
```
is removed or replaced by
```
# Backend:
```
it will work again.

## Expected behavior
The module should probably check if the backend is available at all and not throw errors.
A (semi)automatic migration might also be nice.

## Your Environment
* module businessprocess: v2.5.0
* Icinga Web 2 version and modules (System - About): 2.12.1
* PHP version used (`php --version`):
* Server operating system and version: Ubuntu LTS

**Comment by manfredw** [comment]
Have the same issue (5000+ hosts) with latest icingaweb+modules.
Hosts/services are splitted in several BP config files, default backend is/was icinga-ido.

When switching backend to icingadb, the error is gone as described above, but opening the business process module in icingaweb2 takes much more time. Tested with latest Chrome and Firefox browsers, load time changes from some hundred milliseconds to 4-40s. icingacli based BP checks struggle with errors.
Maybe there are additional issues with icingaweb2, browser developer tools are reporting content-security-policy blockings and "SameSite" cookie attribute warnings.

**Comment by sukhwinder33445** [comment]
Hi @RincewindsHat,
I cannot reproduce this bug, can you please write down the steps?

**Comment by sukhwinder33445** [comment]
I can reproduce it now.
