### ISSUE TITLE
CLI command: Don't throw error on empty nodes

### ISSUE THREAD

**Issue by log1-c** [Icinga/icingaweb2-module-businessprocess#440]
## Describe the bug
When running the check command against a process with an empty node the check writes an error message into the check output but keeps on working otherwise:
```
ERROR: ErrorException in /usr/share/icingaweb2/modules/businessprocess/application/clicommands/ProcessCommand.php:198 with message: Undefined offset: 128
```

## To Reproduce
Have a process with an empty node:
![image](https://github.com/Icinga/icingaweb2-module-businessprocess/assets/24474580/f5751a04-a32c-4d35-a503-4ef4a94343f4)
## Expected behavior
Don't throw error on empty nodes.

## Your Environment
Icinga Web 2 2.11.3
PHP 7.3.33
Module version 2.4.1, but as the code is the same in 2.5.0 I guess an update wouldn't solve this.

**Comment by sukhwinder33445** [comment]
Hi @log1-c,
can you please share the configuration or explain the steps to reproduce this issue?

I could reproduce it if I add an empty sub node and then check the status of the parent node. But your screenshot does not contain a sub node.

**Comment by log1-c** [comment]
> I could reproduce it if I add an empty sub node and then check the status of the parent node. But your screenshot does not contain a sub node.

That is exactly the setup. The screenshot area is too small (sorry), there is a root node above.
Here is a better one
![image](https://github.com/Icinga/icingaweb2-module-businessprocess/assets/24474580/fd1d0e72-02d9-49f5-bd95-71daf829a3b7)

1. is the business process file
2. is one of the configured processes
3. is the subnode of the process where the check is producing the output
  "Application is the emtpy "sub-sub-node"
