### ISSUE TITLE
[dev.icinga.com #12058]  Mixing operators is not allowed

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#52]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12058

**Created by Anonymous on 2016-06-28 08:25:20 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-11-29 14:24:22 +00:00 (in Redmine)_

---

hi, i have met a problem by using the GUI, if you chose some nodes with the special symbol (+) like this:

app = l28fis11;Application - C01F1128 \[RVS FIS+JIT\]

it will show the problem: Mixing operators is not allowed, the attachment shows the error.......

**Attachments**

* [fehler1.PNG](https://dev.icinga.com/attachments/download/3481/fehler1.PNG) Anonymous - _2016-06-28 08:24:22 +00:00_

**Comment by Thomas-Gelf** [comment]
I created #92 to solve this issue
