### ISSUE TITLE
[dev.icinga.com #12071] bp_status_check command does not realize real BP status. eg.: BP is covered by a downtime but the check command shows critical.

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#53]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12071

**Created by rai_n_air on 2016-06-29 12:52:43 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-12 07:59:23 +00:00 (in Redmine)_

---

Hello,
as you can see in the picture there are two BPs: one red one pink.
The pink one is corered by a downtime the red on ist not covered.
This ist all fine but the bp\_check says critical to both.
I would like to have a check that recognises the "real" state of the BP.
In this case it should say "OK" to the pink one because there is a downtime somewhere in the BP checks which covers the problem, so somebody is (hopefully) working on the Problem and nobody else should be called.
Absolutly perfect would be a comment that says "BP ok with one (two, three...) covered Problems".

All information are there (in the Picture), so if the BP can show it, a check should be able to show it as well.

Kind regards, Rainer

**Attachments**

* [BP.jpg](https://dev.icinga.com/attachments/download/3485/BP.jpg) rai_n_air - _2016-06-29 12:40:15 +00:00_ - _BP red and pink_

**Comment by Thomas-Gelf** [comment]
I'll close this issue. We talked about this and as far as I remember we came up with the possible solution of some kind of "bulk object list" that could solve this requirement. So, this would basically be a new operator with special behavior. In case you remember the details, could you please open a dedicated issue for that feature request?

Thanks,
Thomas
