### ISSUE TITLE
[dev.icinga.com #12182] Creating rules for the State of Business Process

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#55]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12182

**Created by alexbs on 2016-07-20 08:09:12 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-20 21:08:59 +00:00 (in Redmine)_

---

Hi everyone,

right now if a part of a Business Process is critical the whole Business Process is CRITICAL or OK (depending on rule ( AND or OR).
It would be great if you could configure the Business Process in a way that if a part of the Process is Critical
the whole Business Process gets a WARNING state.

Regards
Alex

**Comment by nilmerg** [comment]
@Thomas-Gelf Is this now obsolete since #233?

**Comment by nilmerg** [comment]
Well, I guess that's a *yes*.
