### ISSUE TITLE
[dev.icinga.com #12191] Allow Icinga-Groups into the BP

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#56]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12191

**Created by starflighter on 2016-07-21 05:51:01 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-07-21 05:51:01 +00:00 (in Redmine)_

---

Hi,
it would be nice if their isn't only a 1-to-1 relation between host and services. Groups are also usefull in the BP.
e.g. if you have several locations with a lot of devices than you take them to icinga(2)-groups and the target is a BP with a overview about your locations.

starflighter

**Comment by Thomas-Gelf** [comment]
While "being an overview of your locations" isn't exactly what this module have been built for, I'm aware of the fact that it is used for that and similar tasks. In case your "location" is a custom variable, you could give the [Cube](https://github.com/icinga/icingaweb2-module-cube) module a try.

I'll close this issue, as it should be covered with #14.
