### ISSUE TITLE
[dev.icinga.com #13687] Use ICINGAWEB2 filters in BP addon

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#67]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13687

**Created by yayo on 2016-12-19 15:38:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-12-19 15:38:36 +00:00 (in Redmine)_

---

Hello,
active filters in ICINGAWEB2 should also apply to the BP Addon.
Otherwise you see milion hosts that you are not actually allowed to so and that prolly dont interest you.

I would appreciate that you can only build business process models for hosts & services that you are allowed to see in ICINGAWEB2 too.

**Comment by Thomas-Gelf** [comment]
Just as a reminder for myself, a few notes from a related file:

```
Filter "appserver" = host=-rz-app- & service=jmx

Filter "appserver kunde1" = Filter["appserver"] & _host_customer = kunde1

Process "kunde1" = 1 of: Filter["appserver kunde1"]->group('hostname')

Customer App * => host_name = customer-app-* => service_description = lx-jmx-* | service_description = lx-procs tomcat

Customer App = 1 of: Customer App *

```

**Comment by nilmerg** [comment]
Related to #147

**Comment by nilmerg** [comment]
Hiding in-accessible nodes has been ruled out as too performance heavy in #147. Though, applying the monitoring module's restrictions when adding new nodes is considerable.
