### ISSUE TITLE
[dev.icinga.com #13999] Missing head node when selecting node

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-businessprocess#72]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/13999

**Created by lum3n on 2017-01-13 12:30:14 +00:00**

Assignee: _(none)_
Status: _Resolved_  (closed on _2017-01-13 14:10:30 +00:00_)
Target Version: _(none)_
Last Update: _2017-01-13 14:10:30 +00:00 (in Redmine)_

---

Hi,

when selecting a node to display as url parameter, the selected node itself isn't displayed. Instead only its childs are shown.

Example url for screenshot: http://<host>/icingaweb2/businessprocess/process/show?config=test&mode=tree#!/icingaweb2/businessprocess/process/show?config=test&node=top&mode=tree

The file "test" contains only the process "top". On the left side (when not selecting any node) the process is displayed as intended.

Regards,
lum3n

**Attachments**

* [bp_screen.png](https://dev.icinga.com/attachments/download/4047/bp_screen.png) lum3n - _2017-01-13 12:29:27 +00:00_

**Comment by lum3n** [comment]
Hi Thomas,

okay that may be the intended behaviour. Nevertheless the problem exists that you can't see the relation of nodes among each other. For example in the screenshot in the right business process. How do you see that the relation between "APPL" and "DB" is an "and"?

Regards,
Ken

**Comment by Thomas-Gelf** [comment]
You don't. You also do not see their aggregated state on the right side, do you?

**Comment by lum3n** [comment]
Which aggregated state on the right? Should there be something to see?

**Comment by Thomas-Gelf** [comment]
No, that's the point :D

**Comment by lum3n** [comment]
Whut? :D
First of all, you meant the left side, not the right, didn't you?

And secondly I can't believe that this is the way it should be... really. That the "TOP Process" (see screenshot) isn't there may be ok... but without the "and" on the left, the user has no chance to see how the relation of the second level objects is.
