### ISSUE TITLE
Order of nodes

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-businessprocess#82]
It would be nice to change the order of the businessprocess nodes for example in order of priority independent of the alphabetical name.

**Comment by not24get** [comment]
Like to have this.

Actually, I just change the name in the conf file with prefix number, and without changin the display name. It work's, but would be better to do it with GUI.

Thank's

**Comment by Al2Klimov** [comment]
@mwaldmueller Isn't it easier to find a node if they are sorted alphabetically?

**Comment by mwaldmueller** [comment]
Maybe an alphabetical order is easier for finding, but sometimes it's better to have your own ordering. For example if there are lots of business processes defined, it's easier to have the prio-processes on top of the page without scrolling.

**Comment by Al2Klimov** [comment]
@Thomas-Gelf Again – it's your turn: your opinion, please.
