### ISSUE TITLE
adding a new root node throws an error

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-businessprocess#83]
hello,

when i'm trying to create a new root node i get this message:

```
Fatal error: Call to a member function getName() on null in /usr/share/icingaweb2/modules/businessprocess/application/forms/AddNodeForm.php on line 386
```

![bp-root-node](https://cloud.githubusercontent.com/assets/25298055/22203128/c97f34c0-e16b-11e6-9a7d-cb68e13b09fb.png)

**Comment by Thomas-Gelf** [comment]
This has been introduced with 5f6b359 - thanks for reporting it!
