### ISSUE TITLE
Provide a nice documentation

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-businessprocess#84]
I want to see a nice documentation showing how to get started and explaining the single parts of the module

**Comment by vita2** [comment]
so many changes concerning the documentation, awesome :thumbsup: 

would be nice if you can add some informations for the permissions part. "permissions are stored in the process definitions" is a bit unclear for me :neutral_face:

**Comment by Thomas-Gelf** [comment]
Thank you! A chapter regarding permissions will follow, could you please open a dedicated issue for this so that it doesn't get forgotten? I tagged v2.0.0 a few minutes ago and will close this loooong issue right now

Prost! :clinking_glasses:
