### ISSUE TITLE
wrong position of arrow in tree view

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-businessprocess#86]
hello,

the arrow has a wrong position in tree view if the node doesn't have any childs. 

![bp-padding02](https://cloud.githubusercontent.com/assets/25298055/22284630/752e0c1a-e2e8-11e6-8b9c-d5b1146b0774.png)
![bp-padding01](https://cloud.githubusercontent.com/assets/25298055/22284629/752d555e-e2e8-11e6-889d-d85195d74f5e.png)

**Comment by Thomas-Gelf** [comment]
Thanks for reporting this!
