### ISSUE TITLE
Ability to create notification rules for Business Process dashboards

### ISSUE THREAD

**Issue by rodrigohdez1** [Icinga/icingaweb2-module-businessprocess#90]
Not sure if this possible at all, but it seems like there is no easy way for an end user to create a Business Process dashboard and set notifications or service apply rules for the same using the BP module.
I checked the documentation and it lacks a section on how to set up service objects or apply rules. End users may not have access to the CLI or limited access to the Director module.
If this is already possible by using the Director please disregard this issue.

**Comment by Thomas-Gelf** [comment]
Hi @rodrigohdez1,

we are two days late with 2.0.0, your issue should be addressed by two other existing ones:

* #69 speaks about providing an Import Source for the Icinga Director. We already have a working prototype that not only allows to define related checks in an elegant way but also gives the possibility to distribute process configurations through the Director (for distributed environments). However, this will not be part of 2.0.0 - we'll ship it with a later release
* #84 is the last remaining issue on the [v2.0.0 milestone](https://github.com/Icinga/icingaweb2-module-businessprocess/milestones/2.0.0). Documentation will cover how to create new Business Process definitions and how to add them to custom Dashboards - parts of this are already there. A chapter explaining the CLI check command (how it works, how to configure it) will be added before tag the release

I'll therefore close this issue, in case I missed something please let me know!

Thanks,
Thomas

**Comment by rodrigohdez1** [comment]
Thanks for the feedback, really appreciated.
Keep up the good work! :)
