### ISSUE TITLE
the "add simulation" page redirects back to itself without a simulation

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-businessprocess#93]
hello tom,

could you check the simulation part in latest commit please? when i add a new state to simulate a situation then there is a redirect to the "add simulation" page without the desired simulation.

![bp-simulation-01](https://cloud.githubusercontent.com/assets/25298055/22367888/2d33dffa-e484-11e6-8757-fbed42272d22.png)
![bp-simulation-02](https://cloud.githubusercontent.com/assets/25298055/22367886/2c998b1c-e484-11e6-95c9-a501674c822a.png)

regards

**Comment by Thomas-Gelf** [comment]
That's what happens when refactoring code shortly before the release :laughing: - thanks for reporting this!

**Comment by vita2** [comment]
thanks for fixing the issue :beers:

**Comment by Thomas-Gelf** [comment]
You're welcome! Release is coming closer, just a few missing documentation chapters - and two little related improvements :tada:
