### ISSUE TITLE
Document permissions and restrictions

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-businessprocess#98]
hello tom,

please add some informations for the permissions part. in issue #15 you have written that permissions are stored in the process definitions. is it still necessary to submit some code for this or how does it work?

**Comment by Thomas-Gelf** [comment]
Hi @vita2,

honestly I didn't even try it again before tagging the release, but it worked two month ago and it still should :D So there should be no code necessary. Documentation will follow, it would be great if you could test it for me in the meantime. Basically all you need to do is to write allowed users, groups or roles (or any combination of those) to a file header.

The correct spelling for those properties is `AllowedUsers`, `AllowedGroups` and `AllowedRoles`. Their value needs to be a comma-separated list. As soon as there is one of those headers in a process config file, only users fitting any of those filters, the one listed as `Owner` and users with wildcard permissions are allowed to see the process.

It would have been easy to add form fields for the above, but once we planned doing so immediately other questions arose. When you are allowed to share, to whom should you be able to do so? Should you be allowed to see those users, groups or roles? Should you be allowed to see your own ones? How do you hinder other users from spamming your menu? Should we also add the possibility to share it in a read-only and in a read-write way? Only to specific users?

As this started to become a huuuuge discussion, we decided to defer this feature. Still, don't fear to use those restrictions by manually setting them. They are supported and will not be broken in a future release. At least not without a defined migration path in case we eventually decide to change everything ;-)

**Comment by vita2** [comment]
thanks for the fast response. i've tried to add one of the properties to the header. unfortunately my test user sees only a stracktrace:

```
Invalid argument supplied for foreach()

#0 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Metadata.php(215): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Invalid argumen...', '/usr/share/icin...', 215, Array)
#1 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Metadata.php(161): Icinga\Module\Businessprocess\Metadata->isMemberOfAllowedGroups(Object(Icinga\User))
#2 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Metadata.php(152): Icinga\Module\Businessprocess\Metadata->userCanRead(Object(Icinga\User))
#3 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Storage/LegacyStorage.php(81): Icinga\Module\Businessprocess\Metadata->canRead()
#4 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Component/Dashboard.php(40): Icinga\Module\Businessprocess\Storage\LegacyStorage->listProcessNames()
#5 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Component/Dashboard.php(105): Icinga\Module\Businessprocess\Web\Component\Dashboard->__construct(Object(Icinga\Authentication\Auth), Object(Icinga\Module\Businessprocess\Storage\LegacyStorage))
#6 /usr/share/icingaweb2/modules/businessprocess/application/controllers/IndexController.php(17): Icinga\Module\Businessprocess\Web\Component\Dashboard::create(Object(Icinga\Authentication\Auth), Object(Icinga\Module\Businessprocess\Storage\LegacyStorage))
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\IndexController->indexAction()
#8 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#13 {main}
```

the config header looks like this:
```
### Business Process Config File ###
#
# Title           : All Services
# Description     : blabla
# Owner           : bradvormkopf
# AllowedGroups   : monitoringusers
# AddToMenu       : yes
# Statetype       : soft
#
###################################
...	
```

in the `roles.ini` file i have add the permission "module/businessprocess" for accessing the module.

**Comment by Thomas-Gelf** [comment]
Seems that I tested this only with users and roles :p At least the code looked like it was copied from the part checking the roles - but roles are different. Could you please pull and try again?

**Comment by vita2** [comment]
sure. i've just pulled the latest commit and tested it again.

the stacktrace is gone but now the user can see all process definitions. also it is possible to unlock and edit them. 

which kind of information can i send for further debugging?

**Comment by Thomas-Gelf** [comment]
@vita2: related issues should have been fixed about 10 days ago, could you please give it another try?

**Comment by vita2** [comment]
you're right. it's working for `AllowedUsers` and `AllowedGroups`. i've got it wrong and didn't put permission properties to all of my businessprocess-files. because of that my demouser had access to all business processes, right? i have assumed that the restricted demouser can only see the business processes which are explicitly allowed for him.


with the `AllowedRoles` property i get a exception:
```
Invalid argument supplied for foreach()

#0 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Metadata.php(244): Icinga\Application\ApplicationBootstrap->Icinga\Application\{closure}(2, 'Invalid argumen...', '/usr/share/icin...', 244, Array)
#1 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Metadata.php(180): Icinga\Module\Businessprocess\Metadata->hasOneOfTheAllowedRoles(Object(Icinga\User))
#2 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Metadata.php(159): Icinga\Module\Businessprocess\Metadata->userCanRead(Object(Icinga\User))
#3 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Storage/LegacyStorage.php(81): Icinga\Module\Businessprocess\Metadata->canRead()
#4 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Component/Dashboard.php(40): Icinga\Module\Businessprocess\Storage\LegacyStorage->listProcessNames()
#5 /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/Web/Component/Dashboard.php(105): Icinga\Module\Businessprocess\Web\Component\Dashboard->__construct(Object(Icinga\Authentication\Auth), Object(Icinga\Module\Businessprocess\Storage\LegacyStorage))
#6 /usr/share/icingaweb2/modules/businessprocess/application/controllers/IndexController.php(17): Icinga\Module\Businessprocess\Web\Component\Dashboard::create(Object(Icinga\Authentication\Auth), Object(Icinga\Module\Businessprocess\Storage\LegacyStorage))
#7 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Businessprocess\Controllers\IndexController->indexAction()
#8 /usr/share/icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch('indexAction')
#9 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#10 /usr/share/icingaweb2/library/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#11 /usr/share/icingaweb2/library/Icinga/Application/webrouter.php(104): Icinga\Application\Web->dispatch()
#12 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/icin...')
#13 {main}
```

`/etc/icingaweb2/roles.ini`
```
...
[bptest]
permissions = "modules/businessprocess, module/monitoring"
users = "demouser"
```

`/etc/icingaweb2/modules/businessprocess/processes/test.conf`
```
### Business Process Config File ###
#
# Title           : Permissions Test
# Owner           : adminuser
# AllowedRoles    : bptest
# AddToMenu       : yes
# Statetype       : soft
#
###################################

test =
display 1;test;test123
```

**Comment by Thomas-Gelf** [comment]
Could you please give it another try?

**Comment by vita2** [comment]
it' working now :) thank you 🍻

**Comment by Thomas-Gelf** [comment]
Glad to hear that - and sorry for the delay.

Cheers, :wine_glass: 
Thomas
