### ISSUE TITLE
checkboxes in simulation form not accessible

### ISSUE THREAD

**Issue by vita2** [Icinga/icingaweb2-module-businessprocess#99]
hey tom,

in the simulation form i can choose the state of a service and the fact if the service should be acknowledged or in downtime. could you modify the two checkboxes please? at the moment they are invisible or not clickable.

![bp-simulation-css-01](https://cloud.githubusercontent.com/assets/25298055/22380291/4116814c-e4bd-11e6-939d-5aef02faa420.png)

**Comment by Thomas-Gelf** [comment]
Strange, seems to be a chrome-issue with appearance: none - thanks for pointing me to this.
